// Static Site Export Functionality
import React, { useState, useCallback, useMemo } from 'react';
import { cn } from '../../../lib/utils';
import { Block, GlobalStyles, SitePage } from '../types';
import { useEditorStore } from '../store/editor-store';
import { BLOCK_DEFINITIONS } from '../registry';
import {
  Download,
  FileCode,
  FolderOpen,
  Archive,
  Check,
  X,
  Loader2,
  Settings,
  Code,
  Eye,
  Copy,
  ExternalLink,
  Server,
  Globe,
  FileText,
  Image,
  Cloud,
} from 'lucide-react';

// Export options
export interface ExportOptions {
  format: 'html' | 'zip' | 'json';
  includeAssets: boolean;
  minify: boolean;
  inlineStyles: boolean;
  generateSitemap: boolean;
  generateRobots: boolean;
  basePath: string;
  prettyUrls: boolean;
  outputDir: string;
}

// Export result
export interface ExportResult {
  success: boolean;
  files: GeneratedFile[];
  errors: string[];
  warnings: string[];
  totalSize: number;
  duration: number;
}

// Generated file
export interface GeneratedFile {
  path: string;
  content: string | Blob;
  size: number;
  type: 'html' | 'css' | 'js' | 'json' | 'asset' | 'other';
}

// Default export options
const DEFAULT_EXPORT_OPTIONS: ExportOptions = {
  format: 'zip',
  includeAssets: true,
  minify: false,
  inlineStyles: true,
  generateSitemap: true,
  generateRobots: true,
  basePath: '/',
  prettyUrls: true,
  outputDir: 'dist',
};

// Generate HTML for a page
const generatePageHTML = (
  blocks: Block[],
  globalStyles: GlobalStyles,
  options: ExportOptions,
  page: { title: string; slug: string; seoTitle?: string; seoDescription?: string }
): string => {
  // Generate CSS variables from global styles
  const cssVariables = `
    :root {
      --color-primary: ${globalStyles.primaryColor};
      --color-secondary: ${globalStyles.secondaryColor};
      --color-accent: ${globalStyles.accentColor};
      --color-background: ${globalStyles.backgroundColor};
      --color-text: ${globalStyles.textColor};
      --font-body: ${globalStyles.fontFamily};
      --font-heading: ${globalStyles.headingFont};
      --radius: var(--radius-${globalStyles.borderRadius});
      --button-style: ${globalStyles.buttonStyle};
    }
  `;

  // Generate block HTML
  const blocksHTML = blocks.map(block => {
    const definition = BLOCK_DEFINITIONS[block.type];
    if (!definition) return '';

    // Generate block HTML based on type
    return generateBlockHTML(block, globalStyles);
  }).join('\n');

  // Generate full HTML document
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${page.seoTitle || page.title}</title>
  ${page.seoDescription ? `<meta name="description" content="${page.seoDescription}">` : ''}
  <meta name="generator" content="Omugwo Academy Site Builder">
  
  <!-- Tailwind CSS -->
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            primary: '${globalStyles.primaryColor}',
            secondary: '${globalStyles.secondaryColor}',
            accent: '${globalStyles.accentColor}',
          },
          fontFamily: {
            body: '${globalStyles.fontFamily}',
            heading: '${globalStyles.headingFont}',
          }
        }
      }
    }
  </script>
  
  ${options.inlineStyles ? `<style>${cssVariables}</style>` : '<link rel="stylesheet" href="/styles.css">'}
  
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body class="font-body bg-background text-text antialiased">
  ${blocksHTML}
  
  ${options.minify ? '' : '<!-- Generated by Omugwo Academy Site Builder -->'}
</body>
</html>`;

  return options.minify ? minifyHTML(html) : html;
};

// Generate HTML for a single block
const generateBlockHTML = (block: Block, globalStyles: GlobalStyles): string => {
  const props = block.props;
  
  // Map common block types to HTML
  switch (block.type) {
    case 'hero':
      return `
        <section class="relative ${props.paddingY || 'py-32'} overflow-hidden" style="background-image: url('${props.backgroundImage}'); background-size: cover; background-position: center;">
          ${props.showOverlay ? `<div class="absolute inset-0 bg-black/${props.overlayOpacity || 50}"></div>` : ''}
          <div class="${props.containerSize || 'max-w-7xl'} mx-auto px-4 relative z-10 text-${props.align || 'center'}">
            <h1 class="text-4xl md:text-6xl font-bold text-white mb-6">${props.title}</h1>
            <p class="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">${props.subtitle}</p>
            <div class="flex flex-wrap gap-4 justify-${props.align || 'center'}">
              <a href="${props.ctaLink}" class="px-8 py-4 bg-primary text-white font-bold rounded-lg hover:bg-primary/90 transition-colors">${props.ctaText}</a>
              ${props.secondaryCtaText ? `<a href="${props.secondaryCtaLink}" class="px-8 py-4 border border-white text-white font-bold rounded-lg hover:bg-white/10 transition-colors">${props.secondaryCtaText}</a>` : ''}
            </div>
          </div>
        </section>
      `;

    case 'features':
      return `
        <section class="${props.paddingY || 'py-24'} bg-${props.backgroundColor || 'white'}">
          <div class="${props.containerSize || 'max-w-7xl'} mx-auto px-4">
            <div class="text-center mb-16">
              <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">${props.title}</h2>
              ${props.subtitle ? `<p class="text-xl text-gray-600">${props.subtitle}</p>` : ''}
            </div>
            <div class="grid md:grid-cols-${props.columns || 3} gap-8">
              ${(props.features || []).map((feature: any) => `
                <div class="text-center p-6 rounded-xl hover:shadow-lg transition-shadow">
                  <div class="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                    <span class="text-2xl text-primary">${feature.icon}</span>
                  </div>
                  <h3 class="text-xl font-bold text-gray-900 mb-2">${feature.title}</h3>
                  <p class="text-gray-600">${feature.description}</p>
                </div>
              `).join('')}
            </div>
          </div>
        </section>
      `;

    case 'cta':
      return `
        <section class="${props.paddingY || 'py-24'} bg-${props.backgroundColor || 'primary'}">
          <div class="${props.containerSize || 'max-w-4xl'} mx-auto px-4 text-${props.align || 'center'}">
            <h2 class="text-3xl md:text-4xl font-bold text-white mb-4">${props.title}</h2>
            ${props.subtitle ? `<p class="text-xl text-white/90 mb-8">${props.subtitle}</p>` : ''}
            <div class="flex flex-wrap gap-4 justify-${props.align || 'center'}">
              <a href="${props.primaryHref}" class="px-8 py-4 bg-white text-primary font-bold rounded-lg hover:bg-gray-100 transition-colors">${props.primaryText}</a>
              ${props.secondaryText ? `<a href="${props.secondaryHref}" class="px-8 py-4 border-2 border-white text-white font-bold rounded-lg hover:bg-white/10 transition-colors">${props.secondaryText}</a>` : ''}
            </div>
          </div>
        </section>
      `;

    case 'testimonials':
      return `
        <section class="${props.paddingY || 'py-24'} bg-${props.backgroundColor || 'gray-50'}">
          <div class="${props.containerSize || 'max-w-7xl'} mx-auto px-4">
            <div class="text-center mb-16">
              <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">${props.title}</h2>
              ${props.subtitle ? `<p class="text-xl text-gray-600">${props.subtitle}</p>` : ''}
            </div>
            <div class="grid md:grid-cols-${props.columns || 3} gap-8">
              ${(props.testimonials || []).map((testimonial: any) => `
                <div class="bg-white p-6 rounded-xl shadow-sm">
                  <div class="flex items-center gap-4 mb-4">
                    <img src="${testimonial.avatar}" alt="${testimonial.name}" class="w-12 h-12 rounded-full object-cover">
                    <div>
                      <p class="font-bold text-gray-900">${testimonial.name}</p>
                      <p class="text-sm text-gray-500">${testimonial.role}</p>
                    </div>
                  </div>
                  <p class="text-gray-600 italic">"${testimonial.content}"</p>
                </div>
              `).join('')}
            </div>
          </div>
        </section>
      `;

    case 'content':
      return `
        <section class="${props.paddingY || 'py-24'} bg-${props.backgroundColor || 'white'}">
          <div class="${props.containerSize || 'max-w-7xl'} mx-auto px-4">
            <div class="grid md:grid-cols-2 gap-12 items-center">
              ${props.imagePosition === 'left' ? `<img src="${props.image}" alt="" class="rounded-xl shadow-lg">` : ''}
              <div>
                ${props.badgeText ? `<span class="inline-block px-3 py-1 bg-primary/10 text-primary text-sm font-medium rounded-full mb-4">${props.badgeText}</span>` : ''}
                <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">${props.title}</h2>
                <div class="text-gray-600 leading-relaxed">${props.body}</div>
              </div>
              ${props.imagePosition === 'right' ? `<img src="${props.image}" alt="" class="rounded-xl shadow-lg">` : ''}
            </div>
          </div>
        </section>
      `;

    case 'navigation':
      return `
        <nav class="bg-${props.backgroundColor || 'white'} border-b border-gray-200 sticky top-0 z-50">
          <div class="max-w-7xl mx-auto px-4">
            <div class="flex items-center justify-between h-16">
              <a href="/" class="text-xl font-bold text-gray-900">${props.brandName || 'Omugwo Academy'}</a>
              <div class="hidden md:flex items-center gap-8">
                ${(props.links || []).map((link: any) => `
                  <a href="${link.href}" class="text-gray-600 hover:text-gray-900 transition-colors">${link.label}</a>
                `).join('')}
              </div>
              <a href="${props.ctaLink || '/courses'}" class="px-4 py-2 bg-primary text-white font-medium rounded-lg hover:bg-primary/90 transition-colors">${props.ctaText || 'Get Started'}</a>
            </div>
          </div>
        </nav>
      `;

    case 'footer':
      return `
        <footer class="bg-${props.variant === 'dark' ? 'gray-900' : 'white'} py-12 border-t border-gray-200">
          <div class="max-w-7xl mx-auto px-4">
            <div class="flex flex-col md:flex-row items-center justify-between gap-4">
              <p class="text-${props.variant === 'dark' ? 'gray-400' : 'gray-600'} text-sm">
                © ${new Date().getFullYear()} ${props.brandName || 'Omugwo Academy'}. All rights reserved.
              </p>
              <div class="flex items-center gap-6">
                ${(props.links || [{ label: 'Privacy', href: '/privacy' }, { label: 'Terms', href: '/terms' }]).map((link: any) => `
                  <a href="${link.href}" class="text-${props.variant === 'dark' ? 'gray-400' : 'gray-600'} hover:text-${props.variant === 'dark' ? 'white' : 'gray-900'} text-sm transition-colors">${link.label}</a>
                `).join('')}
              </div>
            </div>
          </div>
        </footer>
      `;

    default:
      return `<!-- Block type: ${block.type} - Custom rendering required -->`;
  }
};

// Minify HTML
const minifyHTML = (html: string): string => {
  return html
    .replace(/\s+/g, ' ')
    .replace(/>\s+</g, '><')
    .replace(/\s+/g, ' ')
    .trim();
};

// Generate sitemap XML
const generateSitemap = (pages: { slug: string; updatedAt?: string }[], basePath: string): string => {
  const baseUrl = basePath.replace(/\/$/, '');
  
  const urls = pages.map(page => `
    <url>
      <loc>${baseUrl}/${page.slug}</loc>
      ${page.updatedAt ? `<lastmod>${new Date(page.updatedAt).toISOString().split('T')[0]}</lastmod>` : ''}
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
    </url>
  `).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;
};

// Generate robots.txt
const generateRobots = (basePath: string): string => {
  const baseUrl = basePath.replace(/\/$/, '');
  
  return `User-agent: *
Allow: /

Sitemap: ${baseUrl}/sitemap.xml
`;
};

// Export Manager Hook
export const useExportManager = () => {
  const [isExporting, setIsExporting] = useState(false);
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState<ExportResult | null>(null);

  // Export pages
  const exportPages = useCallback(async (
    pages: SitePage[],
    globalStyles: GlobalStyles,
    options: ExportOptions = DEFAULT_EXPORT_OPTIONS
  ): Promise<ExportResult> => {
    setIsExporting(true);
    setProgress(0);
    const startTime = Date.now();
    const files: GeneratedFile[] = [];
    const errors: string[] = [];
    const warnings: string[] = [];

    try {
      // Generate HTML files for each page
      for (let i = 0; i < pages.length; i++) {
        const page = pages[i];
        const blocks = page.status === 'PUBLISHED' ? page.publishedBlocks : page.draftBlocks;
        
        const html = generatePageHTML(blocks, globalStyles, options, {
          title: page.title,
          slug: page.slug,
          seoTitle: page.seoTitle,
          seoDescription: page.seoDescription,
        });

        const filename = options.prettyUrls 
          ? `${page.slug}/index.html`
          : `${page.slug}.html`;

        files.push({
          path: filename,
          content: html,
          size: html.length,
          type: 'html',
        });

        setProgress(Math.round(((i + 1) / pages.length) * 80));
      }

      // Generate sitemap
      if (options.generateSitemap) {
        const sitemap = generateSitemap(pages, options.basePath);
        files.push({
          path: 'sitemap.xml',
          content: sitemap,
          size: sitemap.length,
          type: 'other',
        });
      }

      // Generate robots.txt
      if (options.generateRobots) {
        const robots = generateRobots(options.basePath);
        files.push({
          path: 'robots.txt',
          content: robots,
          size: robots.length,
          type: 'other',
        });
      }

      setProgress(100);

      const totalSize = files.reduce((sum, f) => sum + f.size, 0);

      const exportResult: ExportResult = {
        success: true,
        files,
        errors,
        warnings,
        totalSize,
        duration: Date.now() - startTime,
      };

      setResult(exportResult);
      return exportResult;

    } catch (error) {
      const exportResult: ExportResult = {
        success: false,
        files,
        errors: [String(error)],
        warnings,
        totalSize: 0,
        duration: Date.now() - startTime,
      };

      setResult(exportResult);
      return exportResult;
    } finally {
      setIsExporting(false);
    }
  }, []);

  // Download as ZIP
  const downloadAsZip = useCallback(async (files: GeneratedFile[], filename: string = 'site-export.zip') => {
    // In production, use JSZip or similar library
    // For now, download as individual files
    const mainHtml = files.find(f => f.path.includes('index.html'));
    if (mainHtml && typeof mainHtml.content === 'string') {
      const blob = new Blob([mainHtml.content], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'index.html';
      a.click();
      URL.revokeObjectURL(url);
    }
  }, []);

  // Copy to clipboard
  const copyToClipboard = useCallback(async (content: string) => {
    try {
      await navigator.clipboard.writeText(content);
      return true;
    } catch {
      return false;
    }
  }, []);

  return {
    isExporting,
    progress,
    result,
    exportPages,
    downloadAsZip,
    copyToClipboard,
  };
};

// Export Panel Component
interface ExportPanelProps {
  pages: SitePage[];
  className?: string;
}

export const ExportPanel: React.FC<ExportPanelProps> = ({ pages, className }) => {
  const { globalStyles } = useEditorStore();
  const { isExporting, progress, result, exportPages, downloadAsZip, copyToClipboard } = useExportManager();

  const [options, setOptions] = useState<ExportOptions>(DEFAULT_EXPORT_OPTIONS);
  const [showCode, setShowCode] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleExport = useCallback(async () => {
    await exportPages(pages, globalStyles, options);
  }, [pages, globalStyles, options, exportPages]);

  const handleCopy = useCallback(async (content: string) => {
    const success = await copyToClipboard(content);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [copyToClipboard]);

  const handleDownload = useCallback(() => {
    if (result) {
      downloadAsZip(result.files);
    }
  }, [result, downloadAsZip]);

  return (
    <div className={cn('flex flex-col h-full bg-white dark:bg-gray-900', className)}>
      {/* Header */}
      <div className="p-3 border-b border-gray-200 dark:border-gray-800">
        <h3 className="font-bold text-sm text-gray-900 dark:text-white flex items-center gap-2">
          <Download className="w-4 h-4" />
          Export Site
        </h3>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-3 space-y-4">
        {/* Export Format */}
        <div>
          <label className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-2 block">
            Export Format
          </label>
          <div className="grid grid-cols-3 gap-2">
            {[
              { value: 'html', label: 'HTML', icon: FileCode },
              { value: 'zip', label: 'ZIP', icon: Archive },
              { value: 'json', label: 'JSON', icon: FileText },
            ].map(({ value, label, icon: Icon }) => (
              <button
                key={value}
                onClick={() => setOptions({ ...options, format: value as ExportOptions['format'] })}
                className={cn(
                  'flex flex-col items-center gap-1 p-3 rounded-lg border transition-colors',
                  options.format === value
                    ? 'border-primary-500 bg-primary-50 dark:bg-primary-950/30'
                    : 'border-gray-200 dark:border-gray-700 hover:border-gray-300'
                )}
              >
                <Icon className={cn(
                  'w-5 h-5',
                  options.format === value ? 'text-primary-600' : 'text-gray-400'
                )} />
                <span className="text-xs font-medium">{label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Options */}
        <div className="space-y-2">
          <label className="text-xs font-medium text-gray-600 dark:text-gray-400">
            Options
          </label>

          {[
            { key: 'includeAssets', label: 'Include Assets (images, etc.)' },
            { key: 'minify', label: 'Minify HTML/CSS' },
            { key: 'inlineStyles', label: 'Inline CSS Styles' },
            { key: 'generateSitemap', label: 'Generate sitemap.xml' },
            { key: 'generateRobots', label: 'Generate robots.txt' },
            { key: 'prettyUrls', label: 'Pretty URLs (slug/index.html)' },
          ].map(({ key, label }) => (
            <label key={key} className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={options[key as keyof ExportOptions] as boolean}
                onChange={(e) => setOptions({ ...options, [key]: e.target.checked })}
                className="w-4 h-4 rounded border-gray-300 text-primary-600"
              />
              <span className="text-xs text-gray-700 dark:text-gray-300">{label}</span>
            </label>
          ))}
        </div>

        {/* Base Path */}
        <div>
          <label className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-1 block">
            Base URL
          </label>
          <input
            type="url"
            value={options.basePath}
            onChange={(e) => setOptions({ ...options, basePath: e.target.value })}
            placeholder="https://yoursite.com"
            className="w-full px-3 py-2 text-xs bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg"
          />
        </div>

        {/* Pages to export */}
        <div>
          <label className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-2 block">
            Pages ({pages.length})
          </label>
          <div className="max-h-32 overflow-y-auto space-y-1">
            {pages.map(page => (
              <div key={page.id} className="flex items-center gap-2 px-2 py-1 bg-gray-50 dark:bg-gray-800 rounded text-xs">
                <Globe className="w-3 h-3 text-gray-400" />
                <span className="flex-1 truncate">{page.title}</span>
                <span className="text-gray-400">/{page.slug}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Export Progress */}
        {isExporting && (
          <div className="p-4 bg-gray-50 dark:bg-gray-800 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Loader2 className="w-4 h-4 animate-spin text-primary-600" />
              <span className="text-sm font-medium">Exporting...</span>
            </div>
            <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2">
              <div
                className="bg-primary-600 h-2 rounded-full transition-all"
                style={{ width: `${progress}%` }}
              />
            </div>
            <p className="text-xs text-gray-500 mt-2">{progress}% complete</p>
          </div>
        )}

        {/* Export Result */}
        {result && !isExporting && (
          <div className={cn(
            'p-4 rounded-lg',
            result.success ? 'bg-green-50 dark:bg-green-950/30' : 'bg-red-50 dark:bg-red-950/30'
          )}>
            <div className="flex items-center gap-2 mb-2">
              {result.success ? (
                <Check className="w-4 h-4 text-green-600" />
              ) : (
                <X className="w-4 h-4 text-red-600" />
              )}
              <span className={cn(
                'text-sm font-medium',
                result.success ? 'text-green-700 dark:text-green-400' : 'text-red-700 dark:text-red-400'
              )}>
                {result.success ? 'Export Complete!' : 'Export Failed'}
              </span>
            </div>

            {result.success && (
              <div className="text-xs text-gray-600 dark:text-gray-400 space-y-1">
                <p>{result.files.length} files generated</p>
                <p>Total size: {(result.totalSize / 1024).toFixed(2)} KB</p>
                <p>Duration: {result.duration}ms</p>
              </div>
            )}

            {result.errors.length > 0 && (
              <div className="mt-2 text-xs text-red-600">
                {result.errors.map((error, i) => (
                  <p key={i}>{error}</p>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Generated Files Preview */}
        {result && result.success && (
          <div>
            <label className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-2 block">
              Generated Files
            </label>
            <div className="space-y-1 max-h-40 overflow-y-auto">
              {result.files.map((file, i) => (
                <div key={i} className="flex items-center gap-2 px-2 py-1.5 bg-gray-50 dark:bg-gray-800 rounded text-xs">
                  <FileCode className="w-3 h-3 text-gray-400" />
                  <span className="flex-1 truncate">{file.path}</span>
                  <span className="text-gray-400">{(file.size / 1024).toFixed(1)}KB</span>
                  <button
                    onClick={() => setShowCode(showCode === file.path ? null : file.path)}
                    className="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded"
                  >
                    <Eye className="w-3 h-3" />
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Code Preview Modal */}
      {showCode && result && (
        <div className="absolute inset-0 bg-black/50 flex items-center justify-center z-10 p-4">
          <div className="bg-white dark:bg-gray-900 rounded-lg max-w-2xl w-full max-h-[80vh] flex flex-col">
            <div className="flex items-center justify-between p-3 border-b border-gray-200 dark:border-gray-800">
              <h4 className="font-bold text-sm">{showCode}</h4>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => {
                    const file = result.files.find(f => f.path === showCode);
                    if (file && typeof file.content === 'string') {
                      handleCopy(file.content);
                    }
                  }}
                  className="px-2 py-1 text-xs bg-primary-100 dark:bg-primary-950/30 text-primary-600 rounded"
                >
                  {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                </button>
                <button
                  onClick={() => setShowCode(null)}
                  className="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 rounded"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>
            <div className="flex-1 overflow-auto p-3">
              <pre className="text-xs bg-gray-50 dark:bg-gray-800 p-3 rounded overflow-x-auto">
                <code>{result.files.find(f => f.path === showCode)?.content as string}</code>
              </pre>
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="p-3 border-t border-gray-200 dark:border-gray-800">
        <button
          onClick={handleExport}
          disabled={isExporting || pages.length === 0}
          className="w-full px-4 py-2.5 text-sm font-bold text-white bg-primary-600 rounded-lg hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
        >
          {isExporting ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Exporting...
            </>
          ) : (
            <>
              <Download className="w-4 h-4" />
              Export Site
            </>
          )}
        </button>

        {result && result.success && (
          <button
            onClick={handleDownload}
            className="w-full mt-2 px-4 py-2 text-sm font-medium text-primary-600 bg-primary-50 dark:bg-primary-950/30 rounded-lg hover:bg-primary-100 dark:hover:bg-primary-950/50"
          >
            Download Files
          </button>
        )}
      </div>
    </div>
  );
};

export default ExportPanel;
