import { Block, Template } from "./types";
import { BLOCK_DEFINITIONS } from "./registry";
import { COURSE_SALES_TEMPLATES } from "./course-sales-templates";
import { COURSE_LAYOUT_TEMPLATES } from "./course-layout-templates";

const id = () => Math.random().toString(36).substr(2, 9);

const NAV = { brandName: "Omugwo Academy", ctaText: "Start Learning", ctaLink: "/courses", variant: "light", paddingY: "py-4", containerSize: "max-w-7xl", menuItems: [{ label: "Home", href: "/" }, { label: "About", href: "/about" }, { label: "Courses", href: "/courses" }, { label: "Community", href: "/community" }, { label: "Webinars", href: "/webinars" }, { label: "Contact", href: "/contact" }] };
const FTR = { brandName: "Omugwo Academy", variant: "dark", paddingY: "py-16", containerSize: "max-w-7xl", menuItems: [{ label: "Home", href: "/" }, { label: "About", href: "/about" }, { label: "Courses", href: "/courses" }, { label: "Community", href: "/community" }, { label: "Webinars", href: "/webinars" }, { label: "Contact", href: "/contact" }] };

export const EXACT_REPLICA_TEMPLATES: Template[] = [
{
    id: "omugwo-default-home", name: "Omugwo Academy Home", description: "The primary landing page for Omugwo Academy", thumbnail: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=400", category: "landing", pageType: "homepage", tags: ["official", "landing", "omugwo"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero", label: "Main Hero", props: { variant: "centered", fullHeight: true, title: "Modern Postnatal Education for African Families", titleHighlight: "African Families", subtitle: "Bridging tradition and science for a healthier motherhood journey. Expert-led courses, supportive community, and culturally relevant guidance.", ctaText: "Start Learning", ctaLink: "/courses", secondaryCtaText: "Watch Free Masterclass", secondaryCtaLink: "/webinars/free-masterclass", backgroundImage: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=1920", align: "left", showOverlay: true, overlayType: "gradient-side-light", overlayOpacity: 100, badgeText: "Omugwo Academy", badgeIcon: "heart", showSocialProof: true, socialProofText: "15,000+ families supported", showRating: true, paddingY: "py-32", containerSize: "max-w-4xl", socialProofAvatars: [{ url: "https://i.pravatar.cc/100?img=11" }, { url: "https://i.pravatar.cc/100?img=12" }, { url: "https://i.pravatar.cc/100?img=13" }, { url: "https://i.pravatar.cc/100?img=14" }] } },
        { id: id(), type: "content", label: "The Challenge", props: { badgeText: "The Challenge", badgeVariant: "warning", title: "Why Postnatal Care in Africa Needs Modernization", body: "The traditional \"Omugwo\" practice where experienced mothers guide new parents is fading as families become more nuclear and geographically dispersed.\n\nNew mothers are left navigating postpartum challenges alone, often without access to reliable information that respects their cultural context while meeting modern medical standards.\n\n**We're rebuilding the village digitally.**", image: "https://images.unsplash.com/photo-1609220136736-443140cffec6?auto=format&fit=crop&q=80&w=800", imagePosition: "right", imageEffect: "animated-blob", backgroundColor: "#f9fafb", paddingY: "py-32", containerSize: "max-w-7xl", ctaText: "", ctaLink: "" } },
        { id: id(), type: "features", label: "Motherhood Journey", props: { variant: "cards", align: "center", title: "Motherhood is a Journey", subtitle: "And we're here to guide you through every stage with expert knowledge and compassionate support.", columns: "3", paddingY: "py-32", containerSize: "max-w-7xl", backgroundColor: "#ffffff", features: [{ badge: "Stage 01", title: "Labour & Delivery", description: "Discover the wonders of childbirth and make informed decisions about your birth plan, pain management, and medical support.", icon: "baby" }, { badge: "Stage 02", title: "Post-Delivery Care", description: "Your comprehensive guide to a smooth and supportive transition to parenthood, focusing on recovery and emotional wellbeing.", icon: "heart" }, { badge: "Stage 03", title: "Baby's First Year", description: "Navigate the beautiful challenges of your baby's growth, from breastfeeding and sleep patterns to developmental milestones.", icon: "users" }] } },
        { id: id(), type: "course_grid", label: "Courses Preview", props: { badgeText: "Our Courses", title: "Expert-Led Learning Paths", subtitle: "Comprehensive courses designed by medical professionals, tailored for African families.", columns: "3", mode: "static", showViewAll: true, backgroundColor: "rgba(245, 243, 255, 0.5)", paddingY: "py-32", containerSize: "max-w-7xl", courses: [{ title: "The Omugwo Masterclass for Moms", description: "Complete postnatal guide covering body recovery, mental health, cultural balance, marriage & intimacy, and infant care.", image: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=800", price: 49000, lessons: 48, duration: "12 Hours", badge: "Most Popular", rating: 5, students: 12000 }, { title: "Partner Support Training", description: "Essential knowledge for fathers and partners to provide meaningful support during the postnatal period.", image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&q=80&w=800", price: 29000, lessons: 24, duration: "6 Hours", rating: 5, students: 5400 }, { title: "Essential Postnatal Care", description: "Core fundamentals every parent needs to know for a healthy postpartum journey.", image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=800", price: 39000, lessons: 32, duration: "8 Hours", rating: 5, students: 8200 }] } },
        { id: id(), type: "content", label: "Meet the Founder", props: { badgeText: "Meet the Founder", badgeVariant: "default", title: "A Personal Journey, A Global Mission", body: "**Dr. Megor Ikuenobe** is a distinguished medical professional and early childhood development specialist on a mission to provide every child in Africa with a promising start.\n\nAs the founder of Lead Oak Women and Children Foundation, she has been a relentless advocate for education, healthcare, and empowerment in communities across Nigeria.\n\nOmugwo Academy was born from her vision to digitize the traditional support system, making expert postnatal guidance accessible to every African family.", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800", imagePosition: "left", imageEffect: "animated-blob", quoteText: "\"Every child deserves a promising start, and every mother deserves support.\"", ctaText: "Read Our Story", ctaLink: "/about", ctaVariant: "outline", backgroundColor: "#ffffff", paddingY: "py-32", containerSize: "max-w-7xl" } },
        { id: id(), type: "campaign_story", label: "My Omugwo Story", props: { badgeText: "Featured Campaign", title: "My ", titleHighlight: "Omugwo", titleSuffix: " Story", body1: "The \"My Omugwo Story\" campaign aims to highlight the transformative power of omugwo care by sharing real-life experiences of new moms, new dads, and close relatives who have benefited from this tradition.", body2: "Whether your journey was filled with challenges, triumphs, or a combination of both, we want to hear your story.", listTitle: "How to Share Your Omugwo Story:", listSubtitle: "We offer three convenient ways to share your omugwo story:", listItems: "Video Submission / walk in video recording\nPodcast Feature\nWritten Article\nLive videos", ctaText: "SHARE YOUR STORY", ctaLink: "#", image1: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=400", image2: "https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=400", image3: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400", image4: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=400", backgroundColor: "#ffffff", paddingY: "py-32", containerSize: "max-w-7xl", borderColor: "#f3f4f6" } },
        { id: id(), type: "testimonials", label: "Testimonials", props: { variant: "cards", title: "Trusted by Thousands of Families", subtitle: "Real stories from real parents who transformed their postnatal experience with Omugwo Academy.", columns: "3", backgroundColor: "#111827", textColor: "#ffffff", paddingY: "py-32", containerSize: "max-w-7xl", badgeText: "Testimonials", testimonials: [{ name: "Adaeze Okonkwo", role: "First-time Mom, Lagos", content: "Omugwo Academy changed everything for me. The blend of traditional wisdom with modern medical advice gave me confidence I never knew I needed.", avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=200", rating: 5 }, { name: "Chukwuemeka Eze", role: "New Dad, Abuja", content: "As a father, I felt lost during my wife's postpartum period. The Dads Course equipped me with practical skills to support her meaningfully.", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200", rating: 5 }, { name: "Folake Adeyemi", role: "Mom of 3, Ibadan", content: "Even after three children, I learned so much. The community support is incredible - it truly feels like having a village again.", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200", rating: 5 }] } },
        { id: id(), type: "hero_split", label: "Podcast Section", props: { title: "Beyond Birth with Dr. Megor", subtitle: "Join Dr. Megor as she delves into the depths of parenthood, exploring the joys, challenges, and transformative experiences that come with raising children. Each episode features insightful conversations with leading experts, experienced parents, and Dr. Megor herself, covering a wide range of topics relevant to new moms, new dads, and families. From navigating the first few weeks with a newborn to fostering a healthy and supportive family environment, Beyond Birth with Dr. Megor offers a wealth of knowledge, practical tips, and personal anecdotes to empower parents on their unique parenting paths.\n\nEmbrace the extraordinary journey of parenthood with Beyond Birth with Dr. Megor. Subscribe and Listen Today!", badgeText: "-PODCAST-", ctaText: "VIEW MORE", ctaLink: "/podcast", secondaryCtaText: "SUBSCRIBE", secondaryCtaLink: "/podcast", align: "left", backgroundImage: "", heroImage: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800", imagePosition: "left", imageEffect: "animated-blob", paddingY: "py-32", containerSize: "max-w-7xl", backgroundGradient: "linear-gradient(to right, #fdf4ff, #ffffff, #f3e8ff)", showOverlay: false, fullHeight: false } },
        { id: id(), type: "faq", label: "FAQ", props: { variant: "accordion", title: "Commonly Asked Questions", paddingY: "py-32", containerSize: "max-w-3xl", faqs: [{ question: "What is Omugwo?", answer: "Omugwo is a time-honored Nigerian postnatal care practice where a mother or mother-in-law comes to help care for a new mother and baby." }, { question: "Who are the courses designed for?", answer: "Our courses are designed for expecting mothers, new mothers, fathers/partners, grandmothers, and anyone involved in postnatal care." }, { question: "Is the content medically verified?", answer: "Yes, all our content is developed and reviewed by Dr. Megor Ikuenobe and a team of medical professionals." }, { question: "How long do I have access to the courses?", answer: "Once enrolled, you have lifetime access to the course content, including all future updates." }, { question: "Is there a community I can join?", answer: "Yes! Every course enrollment includes access to our private community where you can connect with other parents, share experiences, ask questions, and receive support from peers and experts." }] } },
        { id: id(), type: "cta", label: "Final Call to Action", props: { title: "Ready to Transform Your Postnatal Journey?", subtitle: "Join thousands of African families who have discovered the power of informed, supported, and culturally relevant postnatal care.", primaryText: "Explore Courses", primaryHref: "/courses", secondaryText: "Book Consultation", secondaryHref: "/contact", variant: "solid", align: "center", paddingY: "py-32", containerSize: "max-w-4xl" } },
        { id: id(), type: "newsletter", label: "Newsletter", props: { title: "Join Our Community", subtitle: "Get weekly tips, resources, and exclusive content delivered to your inbox.", buttonText: "Subscribe", placeholder: "Enter your email", variant: "primary" } },
        { id: id(), type: "footer", label: "Footer", props: { ...FTR, menuItems: [{ label: "Home", href: "/" }, { label: "About", href: "/about" }, { label: "Courses", href: "/courses" }, { label: "Community", href: "/community" }, { label: "Webinars", href: "/webinars" }, { label: "Contact", href: "/contact" }, { label: 'Privacy Policy', href: '/privacy' }, { label: 'Terms of Service', href: '/terms' }, { label: 'Refund Policy', href: '/refund' }] } }
    ]
},
{
    id: "omugwo-about-page", name: "About Page", description: "About Omugwo Academy and our mission", thumbnail: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400", category: "about", pageType: "about", tags: ["about", "mission", "team"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero", label: "About Hero", props: { variant: "centered", fullHeight: false, title: "Our Heritage,\nYour Future", subtitle: "We bridge the gap between traditional African postnatal wisdom and modern medical care, creating a comprehensive support system for new families.", ctaText: "Explore Courses", ctaLink: "/courses", secondaryCtaText: "Watch Our Story", secondaryCtaLink: "#", backgroundImage: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=1920", align: "left", showOverlay: true, overlayType: "gradient", overlayOpacity: 50, badgeText: "About Omugwo Academy", paddingY: "py-32", containerSize: "max-w-7xl" } },
        { id: id(), type: "stats", label: "Stats", props: { title: "", columns: "4", backgroundColor: "#ffffff", paddingY: "py-16", containerSize: "max-w-7xl", stats: [{ value: "15,000+", label: "Families Supported" }, { value: "200+", label: "Expert Lessons" }, { value: "12", label: "Countries Reached" }, { value: "98%", label: "Satisfaction Rate" }] } },
        { id: id(), type: "content", label: "Our Story", props: { badgeText: "Our Story", title: "What is Omugwo?", body: "**Omugwo** is a beautiful Igbo tradition where a new mother's mother or mother-in-law comes to stay and provide support during the postpartum period.\n\nThis practice represents the essence of African communal care. As modern life has scattered families across cities and continents, many new mothers find themselves without this crucial support system. **Omugwo Academy was created to fill this gap.**", image: "https://images.unsplash.com/photo-1609220136736-443140cffec6?auto=format&fit=crop&q=80&w=800", imagePosition: "left", imageEffect: "none", backgroundColor: "#ffffff", paddingY: "py-32", containerSize: "max-w-7xl", ctaText: "", ctaLink: "" } },
        { id: id(), type: "features", label: "Our Values", props: { title: "What We Stand For", subtitle: "", badgeText: "Our Values", columns: "4", backgroundColor: "#f9fafb", paddingY: "py-32", containerSize: "max-w-7xl", features: [{ title: "Cultural Relevance", description: "We honor African traditions while integrating modern medical knowledge.", icon: "heart" }, { title: "Evidence-Based", description: "All content is developed and reviewed by qualified medical professionals.", icon: "book-open" }, { title: "Community First", description: "We believe in the power of shared experiences and collective support.", icon: "users" }, { title: "Accessibility", description: "Quality postnatal education should be available to every family.", icon: "globe" }] } },
        { id: id(), type: "team", label: "Our Team", props: { title: "Meet the Experts", badgeText: "Our Team", subtitle: "Our team of medical professionals and educators are dedicated to transforming postnatal care across Africa.", columns: "4", backgroundColor: "#ffffff", paddingY: "py-32", containerSize: "max-w-7xl", teamMembers: [{ name: "Dr. Megor Ikuenobe", role: "Founder & Lead Educator", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400", bio: "ECD Specialist with over 15 years of experience in maternal and child health across Africa." }, { name: "Nurse Tolani Adewale", role: "Postnatal Care Coordinator", image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=400", bio: "Certified midwife with 20+ years of omugwo experience." }, { name: "Dr. Kofi Mensah", role: "Pediatric Consultant", image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400", bio: "Neonatal care expert specializing in infant development." }, { name: "Dr. Amara Obi", role: "Mental Health Specialist", image: "https://images.unsplash.com/photo-1559839734-2b71f1536785?auto=format&fit=crop&q=80&w=400", bio: "Clinical psychologist focused on postpartum mental health." }] } },
        { id: id(), type: "cta", label: "Final CTA", props: { title: "Join Our Mission", subtitle: "Together, we can ensure every African family has access to the support and knowledge they need.", primaryText: "Start Learning", primaryHref: "/courses", secondaryText: "Partner With Us", secondaryHref: "/contact", variant: "solid", backgroundColor: "#7c3aed", textColor: "#ffffff", align: "center", paddingY: "py-32", containerSize: "max-w-4xl" } },
        { id: id(), type: "footer", label: "Footer", props: FTR }
    ]
},
{
    id: "omugwo-courses-page", name: "Courses Page", description: "Browse our comprehensive course catalog", thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400", category: "courses", pageType: "courses", tags: ["courses", "learning", "education"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero", label: "Courses Hero", props: { variant: "centered", fullHeight: false, title: "Expert-Led Postnatal Education", subtitle: "Comprehensive courses designed by medical professionals, tailored for African families.\nLearn at your own pace with lifetime access.", backgroundImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=1920", align: "center", showOverlay: true, overlayType: "gradient", overlayOpacity: 50, badgeText: "Our Courses", paddingY: "py-24", containerSize: "max-w-4xl" } },
        { id: id(), type: "course_grid", label: "Courses Grid", props: { title: "", subtitle: "", columns: "2", mode: "dynamic", backgroundColor: "#ffffff", paddingY: "py-16", containerSize: "max-w-7xl", showViewAll: false } },
        { id: id(), type: "features", label: "Features", props: { title: "What's Included in Every Course", subtitle: "", columns: "4", backgroundColor: "#f9fafb", paddingY: "py-16", containerSize: "max-w-7xl", features: [{ title: "Video Lessons", description: "HD quality with transcripts", icon: "book-open" }, { title: "Resources", description: "Downloadable guides & checklists", icon: "file-text" }, { title: "Community", description: "Private support groups", icon: "users" }, { title: "Certificate", description: "Shareable completion badge", icon: "check-circle" }] } },
        { id: id(), type: "cta", label: "Final CTA", props: { title: "Not Sure Where to Start?", subtitle: "Take our free mini-course to get a taste of what Omugwo Academy offers, or book a consultation.", primaryText: "Start Free Course", primaryHref: "/courses/free-mini-course", secondaryText: "Book Consultation", secondaryHref: "/contact", variant: "solid", backgroundColor: "#7c3aed", textColor: "#ffffff", align: "center", paddingY: "py-16", containerSize: "max-w-4xl" } },
        { id: id(), type: "footer", label: "Footer", props: FTR }
    ]
},
{
    id: "omugwo-community-page", name: "Community Page", description: "Join our thriving community of parents", thumbnail: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400", category: "community", pageType: "community", tags: ["community", "social", "support"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero", label: "Community Header", props: { variant: "centered", fullHeight: false, title: "Community", subtitle: "Connect, share, and find support in our global village", backgroundImage: "", backgroundColor: "#f9fafb", align: "left", showOverlay: false, paddingY: "py-12", containerSize: "max-w-7xl", ctaText: "Create Post", ctaLink: "#", secondaryCtaText: "", secondaryCtaLink: "" } },
        { id: id(), type: "community_discussions", label: "Community Discussions", props: { title: "Community Spaces", subtitle: "Find your space and connect with like-minded parents.", mode: "dynamic", posts: [{ title: "New Moms", description: "5,420 members", image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400" }], backgroundColor: "#f9fafb", paddingY: "py-8", containerSize: "max-w-7xl" } },
        { id: id(), type: "footer", label: "Footer", props: FTR }
    ]
},
{
    id: "omugwo-webinars-page", name: "Webinars Page", description: "Join our live webinars and workshops", thumbnail: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=400", category: "webinars", pageType: "webinars", tags: ["webinars", "live", "workshops"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero", label: "Featured Webinar Hero", props: { variant: "centered", fullHeight: false, title: "Free Masterclass: The Modern Omugwo Framework", subtitle: "Discover how to blend traditional postnatal wisdom with modern medical care. Learn the 5 pillars of successful postpartum recovery.", backgroundImage: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=1920", align: "left", showOverlay: true, overlayType: "gradient", overlayOpacity: 90, badgeText: "Free Masterclass", paddingY: "py-24", containerSize: "max-w-7xl", ctaText: "Register Free", ctaLink: "#", secondaryCtaText: "", secondaryCtaLink: "" } },
        { id: id(), type: "webinar_grid", label: "Upcoming Webinars", props: { title: "Upcoming Webinars", subtitle: "", columns: "3", backgroundColor: "#ffffff", paddingY: "py-16", containerSize: "max-w-7xl", webinars: [{ title: "Breastfeeding Success Workshop", description: "Latching techniques, common challenges, and milk supply.", image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800", date: "Mar 1, 2025", time: "10:00 AM WAT", duration: "90 minutes", price: "â‚¦5,000", instructor: "Nurse Tolani Adewale", type: "live" }, { title: "Live Q&A: Postpartum Mental Health", description: "Open discussion about postpartum mental health.", image: "https://images.unsplash.com/photo-1609220136736-443140cffec6?auto=format&fit=crop&q=80&w=800", date: "Mar 5, 2025", time: "5:00 PM WAT", duration: "60 minutes", price: "Free", instructor: "Dr. Amara Obi", type: "live" }] } },
        { id: id(), type: "course_grid", label: "Watch Replays", props: { title: "Watch Replays", subtitle: "", columns: "3", mode: "static", backgroundColor: "#f9fafb", paddingY: "py-16", containerSize: "max-w-7xl", showViewAll: false, courses: [{ title: "Newborn Sleep Patterns Explained", description: "Jan 15, 2025 â€¢ 2,340 views", image: "https://images.unsplash.com/photo-1505576121720-9551e39fbbaf?auto=format&fit=crop&q=80&w=400", duration: "75 min", lessons: 1, price: 0, badge: "Replay" }, { title: "Traditional vs Modern Baby Care", description: "Jan 8, 2025 â€¢ 3,120 views", image: "https://images.unsplash.com/photo-1484981138541-3d074aa97716?auto=format&fit=crop&q=80&w=400", duration: "60 min", lessons: 1, price: 0, badge: "Replay" }, { title: "Partner Support During Postpartum", description: "Dec 20, 2024 â€¢ 1,890 views", image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&q=80&w=400", duration: "55 min", lessons: 1, price: 0, badge: "Replay" }] } },
        { id: id(), type: "cta", label: "Never Miss a Webinar", props: { title: "Never Miss a Webinar", subtitle: "Subscribe to get notified about upcoming live sessions, workshops, and Q&As.", primaryText: "Subscribe", primaryHref: "#", secondaryText: "", secondaryHref: "", variant: "solid", backgroundColor: "#7c3aed", textColor: "#ffffff", align: "center", paddingY: "py-16", containerSize: "max-w-4xl" } },
        { id: id(), type: "footer", label: "Footer", props: FTR }
    ]
},
{
    id: "omugwo-contact-page", name: "Contact Page", description: "Get in touch with us", thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400", category: "contact", pageType: "contact", tags: ["contact", "support", "help"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero", label: "Contact Hero", props: { variant: "centered", fullHeight: false, title: "We're Here to Help", subtitle: "Have questions about our courses or need support? Reach out and we'll respond within 24 hours.", backgroundImage: "", backgroundColor: "#f9fafb", align: "center", showOverlay: false, badgeText: "Contact Us", paddingY: "py-16", containerSize: "max-w-4xl", ctaText: "", ctaLink: "", secondaryCtaText: "", secondaryCtaLink: "" } },
        { id: id(), type: "contact_info", label: "Contact Information", props: { title: "", subtitle: "", columns: "4", backgroundColor: "#ffffff", paddingY: "py-8", containerSize: "max-w-7xl", contactMethods: [{ icon: "mail", title: "Email", description: "", contact: "support@omugwoacademy.com", link: "mailto:support@omugwoacademy.com" }, { icon: "phone", title: "Phone", description: "", contact: "+234 810 555 0123", link: "tel:+2348105550123" }, { icon: "map-pin", title: "Address", description: "", contact: "Omugwo Plaza, Victoria Island, Lagos, Nigeria", link: "" }, { icon: "clock", title: "Hours", description: "", contact: "Mon - Fri: 9AM - 6PM WAT", link: "" }] } },
        { id: id(), type: "contact_form", label: "Contact Form", props: { title: "Send Us a Message", subtitle: "", backgroundColor: "#ffffff", paddingY: "py-16", containerSize: "max-w-4xl", fields: [{ name: "name", label: "Full Name", type: "text", required: true }, { name: "email", label: "Email Address", type: "email", required: true }, { name: "phone", label: "Phone (Optional)", type: "tel", required: false }, { name: "type", label: "What can we help you with?", type: "select", options: ["General Inquiry", "Enrollment Help", "Partnership", "1-on-1 Consultation"], required: true }, { name: "message", label: "Message", type: "textarea", required: true }] } },
        { id: id(), type: "cta", label: "FAQ CTA", props: { title: "Looking for Quick Answers?", subtitle: "Check our FAQ section for answers to commonly asked questions.", primaryText: "View FAQ", primaryHref: "#", secondaryText: "", secondaryHref: "", variant: "outline", backgroundColor: "#f9fafb", textColor: "#111827", align: "center", paddingY: "py-16", containerSize: "max-w-4xl" } },
        { id: id(), type: "footer", label: "Footer", props: FTR }
    ]
},
{ id: "course-sales-premium", name: "Premium Course Sales", description: "High-conversion template for premium courses", thumbnail: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=400", category: "course_sales", pageType: "course_sales", tags: ["sales", "conversion", "course"], blocks: [{ id: id(), type: "navigation", label: "Navigation", props: BLOCK_DEFINITIONS.navigation.defaultProps }, { id: id(), type: "hero_split", label: "Course Hero", props: { title: "Mastering Postpartum Recovery", subtitle: "A comprehensive 12-week program guided by medical experts.", ctaText: "Enroll Now   â‚¦49,000", ctaLink: "#pricing", align: "left", backgroundImage: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=1200" } }, { id: id(), type: "pricing_table", label: "Investment", props: { title: "Join the Masterclass", subtitle: "Lifetime access to all modules and community." } }, { id: id(), type: "testimonials", label: "Success Stories", props: { title: "Join 5,000+ Successful Students", columns: "2" } }, { id: id(), type: "faq", label: "Questions?", props: { title: "Frequently Asked Questions" } }, { id: id(), type: "footer", label: "Footer", props: BLOCK_DEFINITIONS.footer.defaultProps }] },
{ id: "saas-landing-v1", name: "SaaS Launchpad", description: "A sleek landing page for SaaS products.", thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400", category: "landing", pageType: "homepage", tags: ["saas", "tech"], blocks: [{ id: id(), type: "navigation", label: "Header", props: { brandName: "TechApp", variant: "dark", ctaText: "Get Started" } }, { id: id(), type: "hero", label: "Hero", props: { title: "Automate Your Workflow", subtitle: "The ultimate tool for modern teams.", ctaText: "Start Free Trial", variant: "dark", align: "center" } }, { id: id(), type: "features", label: "Features", props: { title: "Powerful Features", columns: "3" } }, { id: id(), type: "pricing_table", label: "Pricing", props: { title: "Simple, transparent pricing" } }, { id: id(), type: "footer", label: "Footer", props: { brandName: "TechApp", variant: "dark" } }] },
{ id: "agency-portfolio-v1", name: "Creative Agency", description: "Showcase your best work.", thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=400", category: "landing", pageType: "homepage", tags: ["agency", "portfolio"], blocks: [{ id: id(), type: "navigation", label: "Header", props: { brandName: "Studio X", variant: "transparent", ctaText: "Let's Talk" } }, { id: id(), type: "hero", label: "Hero", props: { title: "We build digital experiences that inspire.", subtitle: "Award-winning design agency.", ctaText: "View Our Work", align: "left", backgroundImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1920" } }, { id: id(), type: "gallery", label: "Work", props: { title: "Our Projects", columns: "3" } }, { id: id(), type: "footer", label: "Footer", props: { brandName: "Studio X", variant: "dark" } }] },
{ id: "coaching-mentor-v1", name: "Life Coach & Mentor", description: "Build your personal coaching brand.", thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=400", category: "landing", pageType: "about", tags: ["coach", "mentor"], blocks: [{ id: id(), type: "navigation", label: "Header", props: { brandName: "Coach Pro", variant: "light", ctaText: "Book Call" } }, { id: id(), type: "hero", label: "Hero", props: { title: "Unlock Your Full Potential", subtitle: "Break through barriers and achieve your goals.", ctaText: "Book Strategy Session", align: "center", backgroundImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=1920", showOverlay: true } }, { id: id(), type: "features", label: "Services", props: { title: "How We Can Work Together" } }, { id: id(), type: "footer", label: "Footer", props: { brandName: "Coach Pro", variant: "light" } }] },
{ id: "event-webinar-v1", name: "Virtual Summit", description: "Maximize registrations for your event.", thumbnail: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&q=80&w=400", category: "webinar", pageType: "webinar_registration", tags: ["event", "webinar"], blocks: [{ id: id(), type: "navigation", label: "Header", props: { brandName: "Tech Summit 2026", variant: "dark", ctaText: "Save Your Seat" } }, { id: id(), type: "hero", label: "Hero", props: { title: "The Future of AI & Tech", subtitle: "Join 10,000+ industry leaders.", ctaText: "Register for Free", variant: "dark", align: "center", backgroundImage: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&q=80&w=1920" } }, { id: id(), type: "team", label: "Speakers", props: { title: "Keynote Speakers" } }, { id: id(), type: "footer", label: "Footer", props: { brandName: "Tech Summit", variant: "dark" } }] },
{
    id: "omugwo-login-page", name: "Login Page", description: "Authentication login page", thumbnail: "", category: "auth", pageType: "login", tags: ["auth", "login"],
    blocks: [
      { id: id(), type: "navigation", label: "Header", props: NAV },
      { id: id(), type: "content", label: "Login Content", props: { content: "<h1>Login</h1><p>Please use the native authentication form.</p>" } },
      { id: id(), type: "footer", label: "Footer", props: {} }
    ]
},
{
    id: "omugwo-register-page", name: "Register Page", description: "Authentication registration page", thumbnail: "", category: "auth", pageType: "register", tags: ["auth", "register"],
    blocks: [
      { id: id(), type: "navigation", label: "Header", props: NAV },
      { id: id(), type: "content", label: "Register Content", props: { content: "<h1>Register</h1><p>Please use the native registration form.</p>" } },
      { id: id(), type: "footer", label: "Footer", props: {} }
    ]
},
{
    id: "omugwo-forgot-password-page", name: "Forgot Password Page", description: "Authentication forgot password page", thumbnail: "", category: "auth", pageType: "forgot_password", tags: ["auth", "forgot-password"],
    blocks: [
      { id: id(), type: "navigation", label: "Header", props: NAV },
      { id: id(), type: "content", label: "Forgot Password Content", props: { content: "<h1>Forgot Password</h1><p>Please use the native forgot password form.</p>" } },
      { id: id(), type: "footer", label: "Footer", props: {} }
    ]
},
{
    id: "omugwo-share-story-page", name: "Share Your Story", description: "Submit your Omugwo story to be featured", thumbnail: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=400", category: "content", pageType: "custom", tags: ["story", "campaign", "community"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero", label: "Story Hero", props: { variant: "centered", fullHeight: false, title: "Share Your ", titleHighlight: "Omugwo", titleSuffix: " Story", subtitle: "Every mother's journey is unique. Share your postpartum experience to inspire and support other families on their journey.", backgroundImage: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=1920", align: "center", showOverlay: true, overlayType: "gradient", overlayOpacity: 60, badgeText: "My Omugwo Story", paddingY: "py-24", containerSize: "max-w-4xl", ctaText: "", ctaLink: "" } },
        { id: id(), type: "content", label: "About Campaign", props: { badgeText: "About the Campaign", title: "Why Your Story Matters", body: "The \"My Omugwo Story\" campaign highlights the transformative power of omugwo care by sharing real-life experiences of new moms, new dads, and close relatives.\n\nWhether your journey was filled with challenges, triumphs, or a combination of both, your story can help others feel less alone and more prepared for their own postpartum journey.\n\n**Your experience has the power to inspire thousands of families across Africa.**", image: "https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800", imagePosition: "right", backgroundColor: "#ffffff", paddingY: "py-24", containerSize: "max-w-7xl" } },
        { id: id(), type: "features", label: "Ways to Share", props: { variant: "cards", align: "center", title: "How to Share Your Story", subtitle: "Choose the format that works best for you", columns: "3", backgroundColor: "#f9fafb", paddingY: "py-24", containerSize: "max-w-7xl", features: [{ badge: "Option 1", title: "Video Submission", description: "Record a short video sharing your omugwo experience. We'll feature it on our platform and social channels.", icon: "video" }, { badge: "Option 2", title: "Podcast Feature", description: "Join Dr. Megor on the Beyond Birth podcast for a recorded conversation about your journey.", icon: "mic" }, { badge: "Option 3", title: "Written Article", description: "Write your story in your own words. Our editors will help polish it for publication.", icon: "file-text" }] } },
        { id: id(), type: "content", label: "Story Form", props: { badgeText: "Submit Your Story", title: "Tell Us Your Story", body: "Fill out the form below to submit your omugwo story. Our team will review it and reach out within 5-7 business days.\n\n**All stories are reviewed before publication.** We respect your privacy and will only share what you're comfortable with.", image: "", imagePosition: "left", backgroundColor: "#ffffff", paddingY: "py-16", containerSize: "max-w-4xl" } },
        { id: id(), type: "contact_form", label: "Story Submission Form", props: { title: "", subtitle: "", backgroundColor: "#ffffff", paddingY: "py-8", containerSize: "max-w-4xl", fields: [{ name: "name", label: "Full Name", type: "text", required: true }, { name: "email", label: "Email Address", type: "email", required: true }, { name: "phone", label: "Phone (Optional)", type: "tel", required: false }, { name: "story_type", label: "How would you like to share?", type: "select", options: ["Video Submission", "Podcast Feature", "Written Article", "Not Sure Yet"], required: true }, { name: "story_summary", label: "Brief Summary of Your Story", type: "textarea", required: true }] } },
        { id: id(), type: "cta", label: "Questions CTA", props: { title: "Have Questions?", subtitle: "Reach out to our team if you need help or have questions about sharing your story.", primaryText: "Contact Us", primaryHref: "/contact", secondaryText: "", secondaryHref: "", variant: "outline", backgroundColor: "#f9fafb", textColor: "#111827", align: "center", paddingY: "py-16", containerSize: "max-w-4xl" } },
        { id: id(), type: "footer", label: "Footer", props: FTR }
    ]
},
{
    id: "omugwo-podcast-page", name: "Podcast Page", description: "Beyond Birth with Dr. Megor podcast", thumbnail: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=400", category: "content", pageType: "podcast", tags: ["podcast", "audio", "education"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero_split", label: "Podcast Hero", props: { title: "Beyond Birth with ", titleHighlight: "Dr. Megor", subtitle: "Join Dr. Megor as she delves into the depths of parenthood, exploring the joys, challenges, and transformative experiences that come with raising children.\n\nEach episode features insightful conversations with leading experts, experienced parents, and Dr. Megor herself, covering a wide range of topics relevant to new moms, new dads, and families.", ctaText: "Listen Now", ctaLink: "#episodes", secondaryCtaText: "Subscribe", secondaryCtaLink: "#subscribe", align: "left", heroImage: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800", imagePosition: "right", imageEffect: "animated-blob", paddingY: "py-24", containerSize: "max-w-7xl", backgroundGradient: "linear-gradient(to right, #fdf4ff, #ffffff, #f3e8ff)", showOverlay: false, fullHeight: false, badgeText: "-PODCAST-" } },
        { id: id(), type: "features", label: "What You'll Learn", props: { variant: "cards", align: "center", title: "Topics We Cover", subtitle: "Every episode brings you closer to confident parenting", columns: "4", backgroundColor: "#f9fafb", paddingY: "py-24", containerSize: "max-w-7xl", features: [{ title: "Postpartum Recovery", description: "Physical and emotional healing after birth", icon: "heart" }, { title: "Baby Development", description: "Milestones, sleep, and feeding", icon: "baby" }, { title: "Partner Support", description: "Building strong family bonds", icon: "users" }, { title: "Cultural Wisdom", description: "Blending tradition with modern care", icon: "globe" }] } },
        { id: id(), type: "content", label: "Featured Episodes", props: { badgeText: "Latest Episodes", title: "Recent Conversations", body: "Catch up on our latest episodes featuring expert insights and real parent stories.", image: "", imagePosition: "left", backgroundColor: "#ffffff", paddingY: "py-16", containerSize: "max-w-7xl" } },
        { id: id(), type: "course_grid", label: "Episode Grid", props: { title: "", subtitle: "", columns: "3", mode: "static", backgroundColor: "#ffffff", paddingY: "py-8", containerSize: "max-w-7xl", showViewAll: false, courses: [{ title: "The First 40 Days: Traditional Omugwo Practices", description: "Episode 45 • 45 min", image: "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?auto=format&fit=crop&q=80&w=400", duration: "45 min", lessons: 1, price: 0, badge: "Popular" }, { title: "Dads Don't Babysit: Redefining Fatherhood", description: "Episode 44 • 38 min", image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&q=80&w=400", duration: "38 min", lessons: 1, price: 0, badge: "New" }, { title: "Breastfeeding Challenges and Solutions", description: "Episode 43 • 52 min", image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=400", duration: "52 min", lessons: 1, price: 0 }] } },
        { id: id(), type: "cta", label: "Subscribe CTA", props: { title: "Never Miss an Episode", subtitle: "Subscribe on your favorite platform and get new episodes delivered automatically.", primaryText: "Subscribe on Spotify", primaryHref: "#", secondaryText: "Apple Podcasts", secondaryHref: "#", variant: "solid", backgroundColor: "#7c3aed", textColor: "#ffffff", align: "center", paddingY: "py-24", containerSize: "max-w-4xl" } },
        { id: id(), type: "testimonials", label: "Listener Reviews", props: { variant: "cards", title: "What Listeners Say", subtitle: "Join thousands of parents who tune in every week", columns: "3", backgroundColor: "#f9fafb", paddingY: "py-24", containerSize: "max-w-7xl", testimonials: [{ name: "Amaka O.", role: "New Mom, Lagos", content: "This podcast got me through those sleepless nights. Dr. Megor's voice is so calming and the advice is practical.", avatar: "https://i.pravatar.cc/100?img=5", rating: 5 }, { name: "David K.", role: "Father of 2, Abuja", content: "Finally a podcast that speaks to dads too! The episode on fatherhood changed how I support my wife.", avatar: "https://i.pravatar.cc/100?img=8", rating: 5 }, { name: "Fatima B.", role: "Mom of 3, Kano", content: "I learn something new every episode. The cultural perspective makes it so relatable.", avatar: "https://i.pravatar.cc/100?img=9", rating: 5 }] } },
        { id: id(), type: "footer", label: "Footer", props: FTR }
    ]
},
{
    id: "omugwo-faq-page", name: "FAQ Page", description: "Frequently asked questions about Omugwo Academy", thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400", category: "content", pageType: "custom", tags: ["faq", "help", "support"],
    blocks: [
        { id: id(), type: "navigation", label: "Header", props: NAV },
        { id: id(), type: "hero", label: "FAQ Hero", props: { variant: "centered", fullHeight: false, title: "Frequently Asked Questions", subtitle: "Find answers to common questions about our courses, community, and platform.", backgroundImage: "", backgroundColor: "#f9fafb", align: "center", showOverlay: false, badgeText: "Help Center", paddingY: "py-16", containerSize: "max-w-4xl", ctaText: "", ctaLink: "" } },
        { id: id(), type: "faq", label: "General FAQ", props: { variant: "accordion", title: "General Questions", paddingY: "py-8", containerSize: "max-w-3xl", faqs: [{ question: "What is Omugwo Academy?", answer: "Omugwo Academy is a digital platform providing expert-led postnatal education tailored for African families. We blend traditional African postnatal wisdom with modern medical knowledge to support new parents through every stage of their journey." }, { question: "Who are the courses designed for?", answer: "Our courses are designed for expecting mothers, new mothers, fathers/partners, grandmothers, and anyone involved in postnatal care. We have specific courses tailored for each audience." }, { question: "Is the content medically verified?", answer: "Yes, all our content is developed and reviewed by Dr. Megor Ikuenobe and a team of qualified medical professionals. We ensure every lesson meets the highest medical standards while remaining accessible and culturally relevant." }, { question: "How long do I have access to courses?", answer: "Once enrolled, you have lifetime access to the course content, including all future updates. Learn at your own pace without any time pressure." }] } },
        { id: id(), type: "faq", label: "Enrollment FAQ", props: { variant: "accordion", title: "Enrollment & Payment", paddingY: "py-8", containerSize: "max-w-3xl", faqs: [{ question: "What payment methods do you accept?", answer: "We accept all major credit/debit cards, bank transfers, and mobile money payments. For Nigerian users, we also support USSD and card payments through Paystack." }, { question: "Can I get a refund?", answer: "Yes, we offer a 30-day money-back guarantee on all courses. If you're not satisfied with your purchase, contact our support team for a full refund." }, { question: "Can I gift a course to someone?", answer: "Absolutely! During checkout, you can select 'Gift this course' and enter the recipient's email address. They'll receive access instructions via email." }, { question: "Are there group discounts?", answer: "Yes, we offer group discounts for organizations, hospitals, and community groups. Contact us at partnerships@omugwoacademy.com for custom pricing." }] } },
        { id: id(), type: "faq", label: "Technical FAQ", props: { variant: "accordion", title: "Technical & Platform", paddingY: "py-8", containerSize: "max-w-3xl", faqs: [{ question: "Can I access courses on mobile?", answer: "Yes, our platform is fully responsive and works on all devices. You can also download lessons for offline viewing through our mobile app." }, { question: "Do I need special software?", answer: "No special software is required. All you need is a modern web browser and internet connection. Course materials are provided in standard formats (PDF, MP4, etc.)." }, { question: "How do I get a certificate?", answer: "Certificates are automatically generated upon course completion. You can download and share your certificate on LinkedIn or other platforms." }, { question: "Is my data secure?", answer: "Yes, we take data security seriously. All personal information is encrypted and stored securely. We never share your data with third parties without your consent." }] } },
        { id: id(), type: "faq", label: "Community FAQ", props: { variant: "accordion", title: "Community & Support", paddingY: "py-8", containerSize: "max-w-3xl", faqs: [{ question: "How does the community work?", answer: "Every course enrollment includes access to our private community. You can connect with other parents, share experiences, ask questions, and receive support from peers and experts." }, { question: "Can I ask questions directly to instructors?", answer: "Yes! Each course has a Q&A section where you can ask questions. Instructors and teaching assistants respond regularly. Premium members also get access to monthly live Q&A sessions." }, { question: "Is there technical support available?", answer: "Yes, our support team is available Monday-Friday, 9am-6pm WAT. You can reach us via email at support@omugwoacademy.com or through the chat widget on our website." }] } },
        { id: id(), type: "cta", label: "Contact CTA", props: { title: "Still Have Questions?", subtitle: "Can't find what you're looking for? Our support team is here to help.", primaryText: "Contact Support", primaryHref: "/contact", secondaryText: "", secondaryHref: "", variant: "solid", backgroundColor: "#7c3aed", textColor: "#ffffff", align: "center", paddingY: "py-16", containerSize: "max-w-4xl" } },
        { id: id(), type: "footer", label: "Footer", props: FTR }
    ]
}
];

export const TEMPLATES: Template[] = [
    ...EXACT_REPLICA_TEMPLATES,
    ...COURSE_SALES_TEMPLATES,
    ...COURSE_LAYOUT_TEMPLATES
];
