// Lesson Block Registry - Definitions and schemas for the visual lesson editor

import { LessonBlockDefinition, LessonBlockType } from './types';

export const LESSON_BLOCK_DEFINITIONS: Record<LessonBlockType, LessonBlockDefinition> = {
  text: {
    type: 'text',
    label: 'Text',
    icon: 'Type',
    category: 'text',
    description: 'Rich text paragraph with formatting options',
    supportsChildren: false,
    defaultProps: {
      content: '',
      alignment: 'left',
      fontSize: 'base',
      color: '#374151',
    },
    propsSchema: [
      {
        name: 'content',
        label: 'Content',
        type: 'rich-text',
        required: true,
        placeholder: 'Enter your text...',
        group: 'Content',
      },
      {
        name: 'alignment',
        label: 'Alignment',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
          { value: 'justify', label: 'Justify' },
        ],
        defaultValue: 'left',
        group: 'Style',
      },
      {
        name: 'fontSize',
        label: 'Font Size',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'base', label: 'Normal' },
          { value: 'lg', label: 'Large' },
          { value: 'xl', label: 'Extra Large' },
        ],
        defaultValue: 'base',
        group: 'Style',
      },
      {
        name: 'color',
        label: 'Text Color',
        type: 'color',
        defaultValue: '#374151',
        group: 'Style',
      },
    ],
  },

  heading: {
    type: 'heading',
    label: 'Heading',
    icon: 'Heading',
    category: 'text',
    description: 'Section heading with multiple levels',
    supportsChildren: false,
    defaultProps: {
      content: '',
      level: 2,
      alignment: 'left',
      color: '#111827',
    },
    propsSchema: [
      {
        name: 'content',
        label: 'Heading Text',
        type: 'text',
        required: true,
        placeholder: 'Enter heading...',
        group: 'Content',
      },
      {
        name: 'level',
        label: 'Level',
        type: 'select',
        options: [
          { value: '1', label: 'H1 - Main Title' },
          { value: '2', label: 'H2 - Section' },
          { value: '3', label: 'H3 - Subsection' },
          { value: '4', label: 'H4 - Minor Heading' },
          { value: '5', label: 'H5' },
          { value: '6', label: 'H6' },
        ],
        defaultValue: '2',
        group: 'Style',
      },
      {
        name: 'alignment',
        label: 'Alignment',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'left',
        group: 'Style',
      },
      {
        name: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#111827',
        group: 'Style',
      },
    ],
  },

  hero: {
    type: 'hero',
    label: 'Hero Header',
    icon: 'Image',
    category: 'media',
    description: 'Full-width immersive image with overlay text and optional call to action',
    supportsChildren: false,
    defaultProps: {
      image: '',
      title: 'Course Title',
      subtitle: 'Course description or subtitle',
      height: 'large',
      alignment: 'center',
      overlayOpacity: 50,
      overlayColor: '#000000',
    },
    propsSchema: [
      {
        name: 'image',
        label: 'Background Image URL',
        type: 'image',
        required: true,
        placeholder: 'Upload or paste image URL',
        group: 'Image',
      },
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        required: true,
        group: 'Content',
      },
      {
        name: 'subtitle',
        label: 'Subtitle',
        type: 'text',
        group: 'Content',
      },
      {
        name: 'height',
        label: 'Height',
        type: 'select',
        options: [
          { value: 'small', label: 'Small' },
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
          { value: 'full', label: 'Full Screen' },
        ],
        defaultValue: 'large',
        group: 'Style',
      },
      {
        name: 'alignment',
        label: 'Text Alignment',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'center',
        group: 'Style',
      },
      {
        name: 'overlayOpacity',
        label: 'Overlay Opacity (%)',
        type: 'number',
        defaultValue: 50,
        group: 'Style',
      },
      {
        name: 'overlayColor',
        label: 'Overlay Color',
        type: 'color',
        defaultValue: '#000000',
        group: 'Style',
      }
    ],
  },

  image: {
    type: 'image',
    label: 'Image',
    icon: 'Image',
    category: 'media',
    description: 'Image with caption and styling options',
    supportsChildren: false,
    defaultProps: {
      src: '',
      alt: '',
      caption: '',
      alignment: 'center',
      width: 'large',
      borderRadius: 'md',
      shadow: true,
      link: '',
      openInNewTab: false,
    },
    propsSchema: [
      {
        name: 'src',
        label: 'Image URL',
        type: 'image',
        required: true,
        placeholder: 'Upload or paste image URL',
        group: 'Content',
      },
      {
        name: 'alt',
        label: 'Alt Text',
        type: 'text',
        required: true,
        placeholder: 'Describe the image for accessibility',
        group: 'Content',
      },
      {
        name: 'caption',
        label: 'Caption',
        type: 'text',
        placeholder: 'Optional caption text',
        group: 'Content',
      },
      {
        name: 'alignment',
        label: 'Alignment',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'center',
        group: 'Layout',
      },
      {
        name: 'width',
        label: 'Width',
        type: 'select',
        options: [
          { value: 'small', label: 'Small (25%)' },
          { value: 'medium', label: 'Medium (50%)' },
          { value: 'large', label: 'Large (75%)' },
          { value: 'full', label: 'Full Width' },
        ],
        defaultValue: 'large',
        group: 'Layout',
      },
      {
        name: 'borderRadius',
        label: 'Border Radius',
        type: 'select',
        options: [
          { value: 'none', label: 'None' },
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
          { value: 'full', label: 'Rounded' },
        ],
        defaultValue: 'md',
        group: 'Style',
      },
      {
        name: 'shadow',
        label: 'Shadow',
        type: 'boolean',
        defaultValue: true,
        group: 'Style',
      },
      {
        name: 'link',
        label: 'Link URL',
        type: 'url',
        placeholder: 'Optional link when clicked',
        group: 'Link',
      },
      {
        name: 'openInNewTab',
        label: 'Open in New Tab',
        type: 'boolean',
        defaultValue: false,
        group: 'Link',
      },
    ],
  },

  video: {
    type: 'video',
    label: 'Video',
    icon: 'Video',
    category: 'media',
    description: 'Embedded video from YouTube, Vimeo, or upload',
    supportsChildren: false,
    defaultProps: {
      provider: 'youtube',
      videoUrl: '',
      poster: '',
      title: '',
      description: '',
      autoplay: false,
      showControls: true,
      width: 'full',
      aspectRatio: '16:9',
    },
    propsSchema: [
      {
        name: 'provider',
        label: 'Video Provider',
        type: 'select',
        options: [
          { value: 'youtube', label: 'YouTube' },
          { value: 'vimeo', label: 'Vimeo' },
          { value: 'bunny', label: 'Bunny.net' },
          { value: 'upload', label: 'Uploaded File' },
          { value: 'custom', label: 'Custom URL' },
        ],
        defaultValue: 'youtube',
        group: 'Source',
      },
      {
        name: 'videoUrl',
        label: 'Video URL',
        type: 'video',
        required: true,
        placeholder: 'Paste video URL or ID',
        group: 'Source',
      },
      {
        name: 'poster',
        label: 'Poster Image',
        type: 'image',
        placeholder: 'Optional thumbnail image',
        group: 'Source',
      },
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'Video title',
        group: 'Content',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        placeholder: 'Brief video description',
        group: 'Content',
      },
      {
        name: 'width',
        label: 'Width',
        type: 'select',
        options: [
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
          { value: 'full', label: 'Full Width' },
        ],
        defaultValue: 'full',
        group: 'Layout',
      },
      {
        name: 'aspectRatio',
        label: 'Aspect Ratio',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 (Widescreen)' },
          { value: '4:3', label: '4:3 (Standard)' },
          { value: '1:1', label: '1:1 (Square)' },
          { value: '9:16', label: '9:16 (Vertical)' },
        ],
        defaultValue: '16:9',
        group: 'Layout',
      },
      {
        name: 'autoplay',
        label: 'Autoplay',
        type: 'boolean',
        defaultValue: false,
        group: 'Playback',
      },
      {
        name: 'showControls',
        label: 'Show Controls',
        type: 'boolean',
        defaultValue: true,
        group: 'Playback',
      },
    ],
  },

  audio: {
    type: 'audio',
    label: 'Audio',
    icon: 'Music',
    category: 'media',
    description: 'Audio player with optional transcript',
    supportsChildren: false,
    defaultProps: {
      src: '',
      title: '',
      description: '',
      autoplay: false,
      showTranscript: false,
      transcript: '',
    },
    propsSchema: [
      {
        name: 'src',
        label: 'Audio File URL',
        type: 'url',
        required: true,
        placeholder: 'Upload or paste audio URL',
        group: 'Source',
      },
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'Audio title',
        group: 'Content',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        placeholder: 'Brief audio description',
        group: 'Content',
      },
      {
        name: 'autoplay',
        label: 'Autoplay',
        type: 'boolean',
        defaultValue: false,
        group: 'Playback',
      },
      {
        name: 'showTranscript',
        label: 'Show Transcript',
        type: 'boolean',
        defaultValue: false,
        group: 'Transcript',
      },
      {
        name: 'transcript',
        label: 'Transcript',
        type: 'textarea',
        placeholder: 'Full transcript text',
        group: 'Transcript',
      },
    ],
  },

  button: {
    type: 'button',
    label: 'Button',
    icon: 'MousePointer',
    category: 'interactive',
    description: 'Clickable button with link',
    supportsChildren: false,
    defaultProps: {
      text: 'Click Here',
      href: '',
      variant: 'primary',
      size: 'md',
      alignment: 'left',
      openInNewTab: false,
      icon: '',
      iconPosition: 'left',
      fullWidth: false,
    },
    propsSchema: [
      {
        name: 'text',
        label: 'Button Text',
        type: 'text',
        required: true,
        placeholder: 'Button label',
        group: 'Content',
      },
      {
        name: 'href',
        label: 'Link URL',
        type: 'url',
        required: true,
        placeholder: 'https://...',
        group: 'Link',
      },
      {
        name: 'variant',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'primary', label: 'Primary' },
          { value: 'secondary', label: 'Secondary' },
          { value: 'outline', label: 'Outline' },
          { value: 'ghost', label: 'Ghost' },
          { value: 'link', label: 'Link' },
        ],
        defaultValue: 'primary',
        group: 'Style',
      },
      {
        name: 'size',
        label: 'Size',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
        ],
        defaultValue: 'md',
        group: 'Style',
      },
      {
        name: 'alignment',
        label: 'Alignment',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'left',
        group: 'Layout',
      },
      {
        name: 'fullWidth',
        label: 'Full Width',
        type: 'boolean',
        defaultValue: false,
        group: 'Layout',
      },
      {
        name: 'openInNewTab',
        label: 'Open in New Tab',
        type: 'boolean',
        defaultValue: false,
        group: 'Link',
      },
      {
        name: 'icon',
        label: 'Icon',
        type: 'icon',
        placeholder: 'Optional icon name',
        group: 'Icon',
      },
      {
        name: 'iconPosition',
        label: 'Icon Position',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'left',
        group: 'Icon',
      },
    ],
  },

  divider: {
    type: 'divider',
    label: 'Divider',
    icon: 'Minus',
    category: 'structure',
    description: 'Horizontal line to separate content',
    supportsChildren: false,
    defaultProps: {
      style: 'solid',
      thickness: 'thin',
      color: '#e5e7eb',
      width: 'full',
      margin: 'md',
    },
    propsSchema: [
      {
        name: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'solid', label: 'Solid' },
          { value: 'dashed', label: 'Dashed' },
          { value: 'dotted', label: 'Dotted' },
          { value: 'gradient', label: 'Gradient' },
        ],
        defaultValue: 'solid',
        group: 'Style',
      },
      {
        name: 'thickness',
        label: 'Thickness',
        type: 'select',
        options: [
          { value: 'thin', label: 'Thin' },
          { value: 'medium', label: 'Medium' },
          { value: 'thick', label: 'Thick' },
        ],
        defaultValue: 'thin',
        group: 'Style',
      },
      {
        name: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#e5e7eb',
        group: 'Style',
      },
      {
        name: 'width',
        label: 'Width',
        type: 'select',
        options: [
          { value: 'full', label: 'Full Width' },
          { value: 'partial', label: 'Partial (50%)' },
        ],
        defaultValue: 'full',
        group: 'Layout',
      },
      {
        name: 'margin',
        label: 'Spacing',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
          { value: 'xl', label: 'Extra Large' },
        ],
        defaultValue: 'md',
        group: 'Layout',
      },
    ],
  },

  callout: {
    type: 'callout',
    label: 'Callout',
    icon: 'AlertCircle',
    category: 'structure',
    description: 'Highlighted notice or tip box',
    supportsChildren: false,
    defaultProps: {
      variant: 'info',
      title: '',
      content: '',
      icon: 'info',
      dismissible: false,
    },
    propsSchema: [
      {
        name: 'variant',
        label: 'Type',
        type: 'select',
        options: [
          { value: 'info', label: 'Info (Blue)' },
          { value: 'warning', label: 'Warning (Yellow)' },
          { value: 'success', label: 'Success (Green)' },
          { value: 'error', label: 'Error (Red)' },
          { value: 'tip', label: 'Tip (Purple)' },
          { value: 'note', label: 'Note (Gray)' },
        ],
        defaultValue: 'info',
        group: 'Style',
      },
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'Optional callout title',
        group: 'Content',
      },
      {
        name: 'content',
        label: 'Content',
        type: 'textarea',
        required: true,
        placeholder: 'Callout message...',
        group: 'Content',
      },
      {
        name: 'icon',
        label: 'Icon',
        type: 'icon',
        placeholder: 'Icon name',
        group: 'Style',
      },
      {
        name: 'dismissible',
        label: 'Dismissible',
        type: 'boolean',
        defaultValue: false,
        group: 'Behavior',
      },
    ],
  },

  embed: {
    type: 'embed',
    label: 'Embed',
    icon: 'Code',
    category: 'media',
    description: 'Embed external content (forms, widgets, etc.)',
    supportsChildren: false,
    defaultProps: {
      provider: 'custom',
      embedUrl: '',
      embedCode: '',
      width: 'full',
      aspectRatio: '16:9',
      title: '',
    },
    propsSchema: [
      {
        name: 'provider',
        label: 'Provider',
        type: 'select',
        options: [
          { value: 'youtube', label: 'YouTube' },
          { value: 'vimeo', label: 'Vimeo' },
          { value: 'spotify', label: 'Spotify' },
          { value: 'soundcloud', label: 'SoundCloud' },
          { value: 'typeform', label: 'Typeform' },
          { value: 'google-forms', label: 'Google Forms' },
          { value: 'custom', label: 'Custom Embed' },
        ],
        defaultValue: 'custom',
        group: 'Source',
      },
      {
        name: 'embedUrl',
        label: 'Embed URL',
        type: 'url',
        placeholder: 'Paste embed URL',
        group: 'Source',
      },
      {
        name: 'embedCode',
        label: 'Embed Code',
        type: 'code',
        placeholder: '<iframe>...</iframe>',
        group: 'Source',
      },
      {
        name: 'width',
        label: 'Width',
        type: 'select',
        options: [
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
          { value: 'full', label: 'Full Width' },
        ],
        defaultValue: 'full',
        group: 'Layout',
      },
      {
        name: 'aspectRatio',
        label: 'Aspect Ratio',
        type: 'select',
        options: [
          { value: '16:9', label: '16:9 (Widescreen)' },
          { value: '4:3', label: '4:3 (Standard)' },
          { value: '1:1', label: '1:1 (Square)' },
          { value: 'auto', label: 'Auto' },
        ],
        defaultValue: '16:9',
        group: 'Layout',
      },
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'Embed title for accessibility',
        group: 'Content',
      },
    ],
  },

  quote: {
    type: 'quote',
    label: 'Quote',
    icon: 'Quote',
    category: 'text',
    description: 'Blockquote with optional attribution',
    supportsChildren: false,
    defaultProps: {
      content: '',
      author: '',
      source: '',
      alignment: 'left',
      style: 'default',
    },
    propsSchema: [
      {
        name: 'content',
        label: 'Quote',
        type: 'textarea',
        required: true,
        placeholder: 'Enter the quote...',
        group: 'Content',
      },
      {
        name: 'author',
        label: 'Author',
        type: 'text',
        placeholder: 'Who said this?',
        group: 'Attribution',
      },
      {
        name: 'source',
        label: 'Source',
        type: 'text',
        placeholder: 'Book, speech, etc.',
        group: 'Attribution',
      },
      {
        name: 'alignment',
        label: 'Alignment',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
        ],
        defaultValue: 'left',
        group: 'Style',
      },
      {
        name: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'default', label: 'Default' },
          { value: 'highlighted', label: 'Highlighted' },
          { value: 'minimal', label: 'Minimal' },
        ],
        defaultValue: 'default',
        group: 'Style',
      },
    ],
  },

  list: {
    type: 'list',
    label: 'List',
    icon: 'List',
    category: 'text',
    description: 'Bulleted or numbered list',
    supportsChildren: false,
    defaultProps: {
      items: [''],
      ordered: false,
      style: 'default',
      icon: '',
    },
    propsSchema: [
      {
        name: 'items',
        label: 'List Items',
        type: 'textarea',
        required: true,
        placeholder: 'Enter each item on a new line',
        group: 'Content',
      },
      {
        name: 'ordered',
        label: 'Ordered (Numbered)',
        type: 'boolean',
        defaultValue: false,
        group: 'Style',
      },
      {
        name: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'default', label: 'Default' },
          { value: 'checklist', label: 'Checklist' },
          { value: 'numbered', label: 'Numbered' },
          { value: 'icons', label: 'With Icons' },
        ],
        defaultValue: 'default',
        group: 'Style',
      },
      {
        name: 'icon',
        label: 'Icon',
        type: 'icon',
        placeholder: 'Icon for list items',
        group: 'Style',
      },
    ],
  },

  code: {
    type: 'code',
    label: 'Code Block',
    icon: 'Terminal',
    category: 'text',
    description: 'Syntax-highlighted code block',
    supportsChildren: false,
    defaultProps: {
      code: '',
      language: 'javascript',
      showLineNumbers: true,
      showCopyButton: true,
      theme: 'auto',
      title: '',
    },
    propsSchema: [
      {
        name: 'code',
        label: 'Code',
        type: 'code',
        required: true,
        placeholder: 'Paste your code...',
        group: 'Content',
      },
      {
        name: 'language',
        label: 'Language',
        type: 'select',
        options: [
          { value: 'javascript', label: 'JavaScript' },
          { value: 'typescript', label: 'TypeScript' },
          { value: 'python', label: 'Python' },
          { value: 'html', label: 'HTML' },
          { value: 'css', label: 'CSS' },
          { value: 'json', label: 'JSON' },
          { value: 'bash', label: 'Bash' },
          { value: 'sql', label: 'SQL' },
          { value: 'markdown', label: 'Markdown' },
          { value: 'plaintext', label: 'Plain Text' },
        ],
        defaultValue: 'javascript',
        group: 'Content',
      },
      {
        name: 'title',
        label: 'Filename/Title',
        type: 'text',
        placeholder: 'e.g., script.js',
        group: 'Content',
      },
      {
        name: 'showLineNumbers',
        label: 'Show Line Numbers',
        type: 'boolean',
        defaultValue: true,
        group: 'Display',
      },
      {
        name: 'showCopyButton',
        label: 'Show Copy Button',
        type: 'boolean',
        defaultValue: true,
        group: 'Display',
      },
      {
        name: 'theme',
        label: 'Theme',
        type: 'select',
        options: [
          { value: 'light', label: 'Light' },
          { value: 'dark', label: 'Dark' },
          { value: 'auto', label: 'Auto (System)' },
        ],
        defaultValue: 'auto',
        group: 'Display',
      },
    ],
  },

  file: {
    type: 'file',
    label: 'File Download',
    icon: 'Download',
    category: 'interactive',
    description: 'Downloadable file with description',
    supportsChildren: false,
    defaultProps: {
      url: '',
      filename: '',
      description: '',
      fileSize: '',
      fileType: '',
      allowDownload: true,
      openInNewTab: false,
    },
    propsSchema: [
      {
        name: 'url',
        label: 'File URL',
        type: 'url',
        required: true,
        placeholder: 'Upload or paste file URL',
        group: 'File',
      },
      {
        name: 'filename',
        label: 'Filename',
        type: 'text',
        required: true,
        placeholder: 'document.pdf',
        group: 'File',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        placeholder: 'Brief file description',
        group: 'File',
      },
      {
        name: 'fileSize',
        label: 'File Size',
        type: 'text',
        placeholder: 'e.g., 2.4 MB',
        group: 'File',
      },
      {
        name: 'fileType',
        label: 'File Type',
        type: 'text',
        placeholder: 'e.g., PDF',
        group: 'File',
      },
      {
        name: 'allowDownload',
        label: 'Allow Download',
        type: 'boolean',
        defaultValue: true,
        group: 'Behavior',
      },
      {
        name: 'openInNewTab',
        label: 'Open in New Tab',
        type: 'boolean',
        defaultValue: false,
        group: 'Behavior',
      },
    ],
  },

  quiz: {
    type: 'quiz',
    label: 'Quiz',
    icon: 'HelpCircle',
    category: 'interactive',
    description: 'Inline quiz or assessment',
    supportsChildren: false,
    defaultProps: {
      quizId: '',
      title: '',
      description: '',
      passingScore: 70,
      maxAttempts: 3,
      showResults: true,
    },
    propsSchema: [
      {
        name: 'quizId',
        label: 'Quiz ID',
        type: 'text',
        required: true,
        placeholder: 'Select or create quiz',
        group: 'Quiz',
      },
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'Quiz title',
        group: 'Content',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        placeholder: 'Instructions for the quiz',
        group: 'Content',
      },
      {
        name: 'passingScore',
        label: 'Passing Score (%)',
        type: 'number',
        defaultValue: 70,
        group: 'Settings',
      },
      {
        name: 'maxAttempts',
        label: 'Max Attempts',
        type: 'number',
        defaultValue: 3,
        group: 'Settings',
      },
      {
        name: 'showResults',
        label: 'Show Results',
        type: 'boolean',
        defaultValue: true,
        group: 'Settings',
      },
    ],
  },

  reflection: {
    type: 'reflection',
    label: 'Reflection Prompt',
    icon: 'MessageSquare',
    category: 'interactive',
    description: 'Text input for student reflection',
    supportsChildren: false,
    defaultProps: {
      prompt: '',
      placeholder: 'Share your thoughts...',
      minLength: 50,
      maxLength: 2000,
      required: false,
    },
    propsSchema: [
      {
        name: 'prompt',
        label: 'Prompt',
        type: 'textarea',
        required: true,
        placeholder: 'Question or reflection prompt',
        group: 'Content',
      },
      {
        name: 'placeholder',
        label: 'Placeholder Text',
        type: 'text',
        placeholder: 'Share your thoughts...',
        group: 'Content',
      },
      {
        name: 'minLength',
        label: 'Min Characters',
        type: 'number',
        defaultValue: 50,
        group: 'Validation',
      },
      {
        name: 'maxLength',
        label: 'Max Characters',
        type: 'number',
        defaultValue: 2000,
        group: 'Validation',
      },
      {
        name: 'required',
        label: 'Required',
        type: 'boolean',
        defaultValue: false,
        group: 'Validation',
      },
    ],
  },

  // Interactive Components

  flipCard: {
    type: 'flipCard',
    label: 'Flip Card',
    icon: 'RotateCcw',
    category: 'interactive',
    description: 'Interactive card that flips to reveal content on click',
    supportsChildren: false,
    defaultProps: {
      frontContent: 'Click to reveal',
      backContent: 'Hidden content',
      frontImage: '',
      backImage: '',
      flipDirection: 'horizontal',
      color: '#6366f1',
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'frontContent',
        label: 'Front Text',
        type: 'textarea',
        required: true,
        placeholder: 'Content shown before flip',
        group: 'Front',
      },
      {
        name: 'frontImage',
        label: 'Front Image',
        type: 'image',
        placeholder: 'Optional front image',
        group: 'Front',
      },
      {
        name: 'backContent',
        label: 'Back Text',
        type: 'textarea',
        required: true,
        placeholder: 'Content revealed after flip',
        group: 'Back',
      },
      {
        name: 'backImage',
        label: 'Back Image',
        type: 'image',
        placeholder: 'Optional back image',
        group: 'Back',
      },
      {
        name: 'flipDirection',
        label: 'Flip Direction',
        type: 'select',
        options: [
          { value: 'horizontal', label: 'Horizontal' },
          { value: 'vertical', label: 'Vertical' },
        ],
        defaultValue: 'horizontal',
        group: 'Animation',
      },
      {
        name: 'color',
        label: 'Card Color',
        type: 'color',
        defaultValue: '#6366f1',
        group: 'Style',
      },
      {
        name: 'completionRequired',
        label: 'Mark Complete on Flip',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  accordion: {
    type: 'accordion',
    label: 'Accordion',
    icon: 'ChevronDown',
    category: 'interactive',
    description: 'Expandable sections for structured content',
    supportsChildren: false,
    defaultProps: {
      items: [
        { title: 'Section 1', content: 'Content for section 1' },
        { title: 'Section 2', content: 'Content for section 2' },
      ],
      allowMultiple: false,
      style: 'default',
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'items',
        label: 'Accordion Items',
        type: 'json',
        placeholder: '[{"title": "Section", "content": "Content"}]',
        group: 'Content',
      },
      {
        name: 'allowMultiple',
        label: 'Allow Multiple Open',
        type: 'boolean',
        defaultValue: false,
        group: 'Behavior',
      },
      {
        name: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'default', label: 'Default' },
          { value: 'bordered', label: 'Bordered' },
          { value: 'minimal', label: 'Minimal' },
        ],
        defaultValue: 'default',
        group: 'Style',
      },
      {
        name: 'completionRequired',
        label: 'Require All Expanded',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  tabs: {
    type: 'tabs',
    label: 'Tabs',
    icon: 'LayoutGrid',
    category: 'interactive',
    description: 'Organize content into multiple interactive panels',
    supportsChildren: false,
    defaultProps: {
      tabs: [
        { label: 'Tab 1', content: 'Content for tab 1' },
        { label: 'Tab 2', content: 'Content for tab 2' },
      ],
      style: 'default',
      position: 'top',
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'tabs',
        label: 'Tab Items',
        type: 'json',
        placeholder: '[{"label": "Tab", "content": "Content"}]',
        group: 'Content',
      },
      {
        name: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'default', label: 'Default' },
          { value: 'pills', label: 'Pills' },
          { value: 'underline', label: 'Underline' },
        ],
        defaultValue: 'default',
        group: 'Style',
      },
      {
        name: 'position',
        label: 'Tab Position',
        type: 'select',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'left', label: 'Left' },
        ],
        defaultValue: 'top',
        group: 'Layout',
      },
      {
        name: 'completionRequired',
        label: 'Require All Tabs Viewed',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  hotspot: {
    type: 'hotspot',
    label: 'Hotspot Image',
    icon: 'Target',
    category: 'interactive',
    description: 'Clickable areas on images that reveal information',
    supportsChildren: false,
    defaultProps: {
      image: '',
      hotspots: [
        { x: 50, y: 50, label: 'Click me', content: 'Revealed content' },
      ],
      hotspotStyle: 'pulse',
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'image',
        label: 'Background Image',
        type: 'image',
        required: true,
        placeholder: 'Upload base image',
        group: 'Image',
      },
      {
        name: 'hotspots',
        label: 'Hotspots',
        type: 'json',
        placeholder: '[{"x": 50, "y": 50, "label": "Label", "content": "Content"}]',
        group: 'Hotspots',
      },
      {
        name: 'hotspotStyle',
        label: 'Hotspot Style',
        type: 'select',
        options: [
          { value: 'pulse', label: 'Pulsing Dot' },
          { value: 'static', label: 'Static Dot' },
          { value: 'icon', label: 'Icon' },
        ],
        defaultValue: 'pulse',
        group: 'Style',
      },
      {
        name: 'completionRequired',
        label: 'Require All Clicked',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  timeline: {
    type: 'timeline',
    label: 'Timeline',
    icon: 'Clock',
    category: 'interactive',
    description: 'Interactive historical or step-by-step visual explanation',
    supportsChildren: false,
    defaultProps: {
      events: [
        { date: 'Step 1', title: 'First Step', description: 'Description' },
        { date: 'Step 2', title: 'Second Step', description: 'Description' },
      ],
      orientation: 'vertical',
      style: 'default',
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'events',
        label: 'Timeline Events',
        type: 'json',
        placeholder: '[{"date": "Date", "title": "Title", "description": "Description"}]',
        group: 'Content',
      },
      {
        name: 'orientation',
        label: 'Orientation',
        type: 'select',
        options: [
          { value: 'vertical', label: 'Vertical' },
          { value: 'horizontal', label: 'Horizontal' },
        ],
        defaultValue: 'vertical',
        group: 'Layout',
      },
      {
        name: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'default', label: 'Default' },
          { value: 'cards', label: 'Cards' },
          { value: 'minimal', label: 'Minimal' },
        ],
        defaultValue: 'default',
        group: 'Style',
      },
      {
        name: 'completionRequired',
        label: 'Require All Viewed',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  scenario: {
    type: 'scenario',
    label: 'Scenario',
    icon: 'GitBranch',
    category: 'interactive',
    description: 'Branching scenario where choices lead to different outcomes',
    supportsChildren: false,
    defaultProps: {
      title: 'Choose Your Path',
      scenario: {
        id: 'start',
        content: 'You are presented with a choice...',
        choices: [
          { label: 'Option A', nextId: 'a' },
          { label: 'Option B', nextId: 'b' },
        ],
      },
      nodes: [
        { id: 'a', content: 'Outcome A', choices: [] },
        { id: 'b', content: 'Outcome B', choices: [] },
      ],
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'Scenario title',
        group: 'Content',
      },
      {
        name: 'scenario',
        label: 'Start Node',
        type: 'json',
        placeholder: 'Starting scenario node',
        group: 'Content',
      },
      {
        name: 'nodes',
        label: 'Scenario Nodes',
        type: 'json',
        placeholder: 'Array of scenario nodes',
        group: 'Content',
      },
      {
        name: 'completionRequired',
        label: 'Mark Complete on End',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  carousel: {
    type: 'carousel',
    label: 'Carousel',
    icon: 'Images',
    category: 'interactive',
    description: 'Slideshow of images or content cards',
    supportsChildren: false,
    defaultProps: {
      items: [
        { image: '', caption: 'Slide 1' },
        { image: '', caption: 'Slide 2' },
      ],
      autoplay: false,
      autoplaySpeed: 5000,
      showDots: true,
      showArrows: true,
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'items',
        label: 'Slides',
        type: 'json',
        placeholder: '[{"image": "url", "caption": "Caption"}]',
        group: 'Content',
      },
      {
        name: 'autoplay',
        label: 'Auto Play',
        type: 'boolean',
        defaultValue: false,
        group: 'Behavior',
      },
      {
        name: 'autoplaySpeed',
        label: 'Auto Play Speed (ms)',
        type: 'number',
        defaultValue: 5000,
        group: 'Behavior',
      },
      {
        name: 'showDots',
        label: 'Show Dots',
        type: 'boolean',
        defaultValue: true,
        group: 'Navigation',
      },
      {
        name: 'showArrows',
        label: 'Show Arrows',
        type: 'boolean',
        defaultValue: true,
        group: 'Navigation',
      },
      {
        name: 'completionRequired',
        label: 'Require All Viewed',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  slider: {
    type: 'slider',
    label: 'Content Slider',
    icon: 'Sliders',
    category: 'interactive',
    description: 'Interactive slider for comparisons or reveals',
    supportsChildren: false,
    defaultProps: {
      beforeImage: '',
      afterImage: '',
      beforeLabel: 'Before',
      afterLabel: 'After',
      orientation: 'horizontal',
      startPosition: 50,
    },
    propsSchema: [
      {
        name: 'beforeImage',
        label: 'Before Image',
        type: 'image',
        required: true,
        group: 'Images',
      },
      {
        name: 'afterImage',
        label: 'After Image',
        type: 'image',
        required: true,
        group: 'Images',
      },
      {
        name: 'beforeLabel',
        label: 'Before Label',
        type: 'text',
        defaultValue: 'Before',
        group: 'Labels',
      },
      {
        name: 'afterLabel',
        label: 'After Label',
        type: 'text',
        defaultValue: 'After',
        group: 'Labels',
      },
      {
        name: 'orientation',
        label: 'Orientation',
        type: 'select',
        options: [
          { value: 'horizontal', label: 'Horizontal' },
          { value: 'vertical', label: 'Vertical' },
        ],
        defaultValue: 'horizontal',
        group: 'Layout',
      },
      {
        name: 'startPosition',
        label: 'Start Position (%)',
        type: 'number',
        defaultValue: 50,
        group: 'Layout',
      },
    ],
  },

  process: {
    type: 'process',
    label: 'Process Steps',
    icon: 'GitBranch',
    category: 'interactive',
    description: 'Sequential interactive learning flow with steps',
    supportsChildren: false,
    defaultProps: {
      steps: [
        { title: 'Step 1', description: 'First step description', icon: '1' },
        { title: 'Step 2', description: 'Second step description', icon: '2' },
      ],
      style: 'numbered',
      allowNavigation: true,
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'steps',
        label: 'Process Steps',
        type: 'json',
        placeholder: '[{"title": "Step", "description": "Description", "icon": "1"}]',
        group: 'Content',
      },
      {
        name: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'numbered', label: 'Numbered' },
          { value: 'icons', label: 'Icons' },
          { value: 'timeline', label: 'Timeline' },
        ],
        defaultValue: 'numbered',
        group: 'Style',
      },
      {
        name: 'allowNavigation',
        label: 'Allow Free Navigation',
        type: 'boolean',
        defaultValue: true,
        group: 'Behavior',
      },
      {
        name: 'completionRequired',
        label: 'Require All Steps',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  // Assessment Components

  knowledgeCheck: {
    type: 'knowledgeCheck',
    label: 'Knowledge Check',
    icon: 'CheckCircle',
    category: 'interactive',
    description: 'Inline quiz question embedded within lesson content',
    supportsChildren: false,
    defaultProps: {
      question: 'What is the correct answer?',
      type: 'single',
      options: [
        { text: 'Option A', correct: false },
        { text: 'Option B', correct: true },
        { text: 'Option C', correct: false },
      ],
      feedback: { correct: 'Correct!', incorrect: 'Try again.' },
      allowRetry: true,
      showFeedback: true,
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'question',
        label: 'Question',
        type: 'textarea',
        required: true,
        placeholder: 'Enter your question',
        group: 'Question',
      },
      {
        name: 'type',
        label: 'Question Type',
        type: 'select',
        options: [
          { value: 'single', label: 'Single Choice' },
          { value: 'multiple', label: 'Multiple Choice' },
        ],
        defaultValue: 'single',
        group: 'Question',
      },
      {
        name: 'options',
        label: 'Answer Options',
        type: 'json',
        placeholder: '[{"text": "Answer", "correct": true}]',
        group: 'Answers',
      },
      {
        name: 'feedback',
        label: 'Feedback Messages',
        type: 'json',
        placeholder: '{"correct": "Correct!", "incorrect": "Try again"}',
        group: 'Feedback',
      },
      {
        name: 'allowRetry',
        label: 'Allow Retry',
        type: 'boolean',
        defaultValue: true,
        group: 'Behavior',
      },
      {
        name: 'showFeedback',
        label: 'Show Feedback',
        type: 'boolean',
        defaultValue: true,
        group: 'Behavior',
      },
      {
        name: 'completionRequired',
        label: 'Require Correct Answer',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  poll: {
    type: 'poll',
    label: 'Poll',
    icon: 'BarChart2',
    category: 'interactive',
    description: 'Quick survey or opinion poll',
    supportsChildren: false,
    defaultProps: {
      question: 'What do you think?',
      options: [
        { text: 'Option A', votes: 0 },
        { text: 'Option B', votes: 0 },
      ],
      showResults: true,
      allowMultiple: false,
    },
    propsSchema: [
      {
        name: 'question',
        label: 'Question',
        type: 'text',
        required: true,
        placeholder: 'Poll question',
        group: 'Content',
      },
      {
        name: 'options',
        label: 'Poll Options',
        type: 'json',
        placeholder: '[{"text": "Option", "votes": 0}]',
        group: 'Content',
      },
      {
        name: 'showResults',
        label: 'Show Results After Vote',
        type: 'boolean',
        defaultValue: true,
        group: 'Behavior',
      },
      {
        name: 'allowMultiple',
        label: 'Allow Multiple Selections',
        type: 'boolean',
        defaultValue: false,
        group: 'Behavior',
      },
    ],
  },

  matching: {
    type: 'matching',
    label: 'Matching Exercise',
    icon: 'Link',
    category: 'interactive',
    description: 'Match items from two columns',
    supportsChildren: false,
    defaultProps: {
      instructions: 'Match the items correctly',
      pairs: [
        { left: 'Item A', right: 'Match A' },
        { left: 'Item B', right: 'Match B' },
      ],
      shuffle: true,
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'instructions',
        label: 'Instructions',
        type: 'textarea',
        placeholder: 'Instructions for the exercise',
        group: 'Content',
      },
      {
        name: 'pairs',
        label: 'Matching Pairs',
        type: 'json',
        placeholder: '[{"left": "Item", "right": "Match"}]',
        group: 'Content',
      },
      {
        name: 'shuffle',
        label: 'Shuffle Items',
        type: 'boolean',
        defaultValue: true,
        group: 'Behavior',
      },
      {
        name: 'completionRequired',
        label: 'Require All Correct',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  sorting: {
    type: 'sorting',
    label: 'Sorting Exercise',
    icon: 'ListOrdered',
    category: 'interactive',
    description: 'Drag and drop items into correct order',
    supportsChildren: false,
    defaultProps: {
      instructions: 'Arrange items in the correct order',
      items: [
        { text: 'First item', order: 1 },
        { text: 'Second item', order: 2 },
        { text: 'Third item', order: 3 },
      ],
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'instructions',
        label: 'Instructions',
        type: 'textarea',
        placeholder: 'Instructions for the exercise',
        group: 'Content',
      },
      {
        name: 'items',
        label: 'Items to Sort',
        type: 'json',
        placeholder: '[{"text": "Item", "order": 1}]',
        group: 'Content',
      },
      {
        name: 'completionRequired',
        label: 'Require Correct Order',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  fillBlank: {
    type: 'fillBlank',
    label: 'Fill in the Blank',
    icon: 'TextCursor',
    category: 'interactive',
    description: 'Text with blanks for learners to fill',
    supportsChildren: false,
    defaultProps: {
      text: 'The capital of France is [Paris].',
      blanks: [{ id: 'blank1', answer: 'Paris', hints: [] }],
      caseSensitive: false,
      completionRequired: true,
    },
    propsSchema: [
      {
        name: 'text',
        label: 'Text with Blanks',
        type: 'textarea',
        placeholder: 'Use [answer] for blanks',
        group: 'Content',
      },
      {
        name: 'blanks',
        label: 'Blank Answers',
        type: 'json',
        placeholder: '[{"id": "blank1", "answer": "Answer", "hints": []}]',
        group: 'Content',
      },
      {
        name: 'caseSensitive',
        label: 'Case Sensitive',
        type: 'boolean',
        defaultValue: false,
        group: 'Behavior',
      },
      {
        name: 'completionRequired',
        label: 'Require All Correct',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  // Layout Components

  section: {
    type: 'section',
    label: 'Section',
    icon: 'Square',
    category: 'structure',
    description: 'Container for grouping content with optional styling',
    supportsChildren: true,
    defaultProps: {
      title: '',
      background: 'transparent',
      padding: 'md',
      borderRadius: 'lg',
      shadow: false,
      fullWidth: false,
    },
    propsSchema: [
      {
        name: 'title',
        label: 'Section Title',
        type: 'text',
        placeholder: 'Optional section title',
        group: 'Content',
      },
      {
        name: 'background',
        label: 'Background',
        type: 'select',
        options: [
          { value: 'transparent', label: 'Transparent' },
          { value: 'white', label: 'White' },
          { value: 'gray', label: 'Gray' },
          { value: 'primary', label: 'Primary' },
        ],
        defaultValue: 'transparent',
        group: 'Style',
      },
      {
        name: 'padding',
        label: 'Padding',
        type: 'select',
        options: [
          { value: 'none', label: 'None' },
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
        ],
        defaultValue: 'md',
        group: 'Style',
      },
      {
        name: 'borderRadius',
        label: 'Border Radius',
        type: 'select',
        options: [
          { value: 'none', label: 'None' },
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
        ],
        defaultValue: 'lg',
        group: 'Style',
      },
      {
        name: 'shadow',
        label: 'Shadow',
        type: 'boolean',
        defaultValue: false,
        group: 'Style',
      },
      {
        name: 'fullWidth',
        label: 'Full Width',
        type: 'boolean',
        defaultValue: false,
        group: 'Layout',
      },
    ],
  },

  columns: {
    type: 'columns',
    label: 'Columns',
    icon: 'Columns',
    category: 'structure',
    description: 'Multi-column layout for side-by-side content',
    supportsChildren: true,
    defaultProps: {
      count: 2,
      gap: 'md',
      distribution: 'equal',
      stackOnMobile: true,
    },
    propsSchema: [
      {
        name: 'count',
        label: 'Number of Columns',
        type: 'select',
        options: [
          { value: 2, label: '2 Columns' },
          { value: 3, label: '3 Columns' },
          { value: 4, label: '4 Columns' },
        ],
        defaultValue: 2,
        group: 'Layout',
      },
      {
        name: 'gap',
        label: 'Gap Size',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
        ],
        defaultValue: 'md',
        group: 'Layout',
      },
      {
        name: 'distribution',
        label: 'Column Distribution',
        type: 'select',
        options: [
          { value: 'equal', label: 'Equal' },
          { value: 'sidebar-left', label: 'Sidebar Left' },
          { value: 'sidebar-right', label: 'Sidebar Right' },
        ],
        defaultValue: 'equal',
        group: 'Layout',
      },
      {
        name: 'stackOnMobile',
        label: 'Stack on Mobile',
        type: 'boolean',
        defaultValue: true,
        group: 'Responsive',
      },
    ],
  },

  grid: {
    type: 'grid',
    label: 'Grid',
    icon: 'Grid',
    category: 'structure',
    description: 'Flexible grid layout for multiple items',
    supportsChildren: true,
    defaultProps: {
      columns: 3,
      gap: 'md',
      autoFit: false,
      minColumnWidth: 200,
    },
    propsSchema: [
      {
        name: 'columns',
        label: 'Max Columns',
        type: 'number',
        defaultValue: 3,
        group: 'Layout',
      },
      {
        name: 'gap',
        label: 'Gap Size',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
        ],
        defaultValue: 'md',
        group: 'Layout',
      },
      {
        name: 'autoFit',
        label: 'Auto-fit Columns',
        type: 'boolean',
        defaultValue: false,
        group: 'Layout',
      },
      {
        name: 'minColumnWidth',
        label: 'Min Column Width (px)',
        type: 'number',
        defaultValue: 200,
        group: 'Layout',
      },
    ],
  },

  spacer: {
    type: 'spacer',
    label: 'Spacer',
    icon: 'MoveVertical',
    category: 'structure',
    description: 'Add vertical or horizontal spacing',
    supportsChildren: false,
    defaultProps: {
      height: 'md',
      showDivider: false,
      dividerColor: '#e5e7eb',
    },
    propsSchema: [
      {
        name: 'height',
        label: 'Height',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
          { value: 'xl', label: 'Extra Large' },
        ],
        defaultValue: 'md',
        group: 'Size',
      },
      {
        name: 'showDivider',
        label: 'Show Divider',
        type: 'boolean',
        defaultValue: false,
        group: 'Divider',
      },
      {
        name: 'dividerColor',
        label: 'Divider Color',
        type: 'color',
        defaultValue: '#e5e7eb',
        group: 'Divider',
      },
    ],
  },

  // Engagement & Collaboration
  discussion: {
    type: 'discussion',
    label: 'Discussion',
    icon: 'MessageCircle',
    category: 'interactive',
    description: 'Discussion prompt for learner responses',
    supportsChildren: false,
    defaultProps: {
      prompt: 'Share your thoughts...',
      placeholder: 'Type your response...',
      requireResponse: false,
    },
    propsSchema: [
      {
        name: 'prompt',
        label: 'Discussion Prompt',
        type: 'text',
        defaultValue: 'Share your thoughts...',
        group: 'Content',
      },
      {
        name: 'placeholder',
        label: 'Placeholder Text',
        type: 'text',
        defaultValue: 'Type your response...',
        group: 'Content',
      },
      {
        name: 'requireResponse',
        label: 'Require Response',
        type: 'boolean',
        defaultValue: false,
        group: 'Settings',
      },
    ],
  },

  submission: {
    type: 'submission',
    label: 'Submission',
    icon: 'Upload',
    category: 'assessment',
    description: 'File submission area for assignments',
    supportsChildren: false,
    defaultProps: {
      title: 'Submit Your Work',
      description: 'Upload your completed assignment',
      acceptedFormats: ['pdf', 'doc', 'docx', 'jpg', 'png'],
      maxSize: 10,
      allowMultiple: false,
      requireCompletion: true,
    },
    propsSchema: [
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        defaultValue: 'Submit Your Work',
        group: 'Content',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        defaultValue: 'Upload your completed assignment',
        group: 'Content',
      },
      {
        name: 'acceptedFormats',
        label: 'Accepted Formats',
        type: 'json',
        defaultValue: ['pdf', 'doc', 'docx', 'jpg', 'png'],
        group: 'Settings',
      },
      {
        name: 'maxSize',
        label: 'Max Size (MB)',
        type: 'number',
        defaultValue: 10,
        group: 'Settings',
      },
      {
        name: 'allowMultiple',
        label: 'Allow Multiple Files',
        type: 'boolean',
        defaultValue: false,
        group: 'Settings',
      },
      {
        name: 'requireCompletion',
        label: 'Require for Completion',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  exercise: {
    type: 'exercise',
    label: 'Exercise',
    icon: 'Pencil',
    category: 'assessment',
    description: 'Interactive exercise with instructions',
    supportsChildren: false,
    defaultProps: {
      title: 'Practice Exercise',
      instructions: 'Complete this exercise...',
      timeLimit: 0,
      requireCompletion: true,
    },
    propsSchema: [
      {
        name: 'title',
        label: 'Exercise Title',
        type: 'text',
        defaultValue: 'Practice Exercise',
        group: 'Content',
      },
      {
        name: 'instructions',
        label: 'Instructions',
        type: 'textarea',
        defaultValue: 'Complete this exercise...',
        group: 'Content',
      },
      {
        name: 'timeLimit',
        label: 'Time Limit (minutes, 0 = no limit)',
        type: 'number',
        defaultValue: 0,
        group: 'Settings',
      },
      {
        name: 'requireCompletion',
        label: 'Require for Completion',
        type: 'boolean',
        defaultValue: true,
        group: 'Completion',
      },
    ],
  },

  // Resources & Tools
  resource: {
    type: 'resource',
    label: 'Resource',
    icon: 'FileText',
    category: 'media',
    description: 'Downloadable resource or link',
    supportsChildren: false,
    defaultProps: {
      title: 'Resource Title',
      description: 'Resource description',
      type: 'pdf',
      url: '',
      size: '',
      icon: 'file',
    },
    propsSchema: [
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        defaultValue: 'Resource Title',
        group: 'Content',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        defaultValue: 'Resource description',
        group: 'Content',
      },
      {
        name: 'type',
        label: 'Resource Type',
        type: 'select',
        options: [
          { value: 'pdf', label: 'PDF Document' },
          { value: 'video', label: 'Video' },
          { value: 'link', label: 'External Link' },
          { value: 'zip', label: 'ZIP Archive' },
          { value: 'doc', label: 'Document' },
        ],
        defaultValue: 'pdf',
        group: 'Settings',
      },
      {
        name: 'url',
        label: 'URL',
        type: 'text',
        defaultValue: '',
        group: 'Content',
      },
      {
        name: 'size',
        label: 'File Size',
        type: 'text',
        defaultValue: '',
        group: 'Content',
      },
      {
        name: 'icon',
        label: 'Icon',
        type: 'select',
        options: [
          { value: 'file', label: 'File' },
          { value: 'file-text', label: 'Text File' },
          { value: 'video', label: 'Video' },
          { value: 'link', label: 'Link' },
          { value: 'download', label: 'Download' },
        ],
        defaultValue: 'file',
        group: 'Appearance',
      },
    ],
  },

  checklist: {
    type: 'checklist',
    label: 'Checklist',
    icon: 'CheckSquare',
    category: 'interactive',
    description: 'Interactive checklist with progress tracking',
    supportsChildren: false,
    defaultProps: {
      title: 'Task Checklist',
      items: [
        { id: 'item-1', text: 'Task 1', completed: false, required: true },
        { id: 'item-2', text: 'Task 2', completed: false, required: true },
      ],
      showProgress: true,
      requireAll: false,
    },
    propsSchema: [
      {
        name: 'title',
        label: 'Checklist Title',
        type: 'text',
        defaultValue: 'Task Checklist',
        group: 'Content',
      },
      {
        name: 'items',
        label: 'Checklist Items',
        type: 'json',
        defaultValue: [
          { id: 'item-1', text: 'Task 1', completed: false, required: true },
          { id: 'item-2', text: 'Task 2', completed: false, required: true },
        ],
        group: 'Content',
      },
      {
        name: 'showProgress',
        label: 'Show Progress',
        type: 'boolean',
        defaultValue: true,
        group: 'Settings',
      },
      {
        name: 'requireAll',
        label: 'Require All Items',
        type: 'boolean',
        defaultValue: false,
        group: 'Completion',
      },
    ],
  },

  badge: {
    type: 'badge',
    label: 'Badge',
    icon: 'Award',
    category: 'interactive',
    description: 'Achievement badge for gamification',
    supportsChildren: false,
    defaultProps: {
      name: 'Achievement Badge',
      description: 'Complete all tasks to earn this badge',
      icon: '🏆',
      earned: false,
    },
    propsSchema: [
      {
        name: 'name',
        label: 'Badge Name',
        type: 'text',
        defaultValue: 'Achievement Badge',
        group: 'Content',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        defaultValue: 'Complete all tasks to earn this badge',
        group: 'Content',
      },
      {
        name: 'icon',
        label: 'Badge Icon (emoji)',
        type: 'text',
        defaultValue: '🏆',
        group: 'Appearance',
      },
      {
        name: 'earned',
        label: 'Already Earned',
        type: 'boolean',
        defaultValue: false,
        group: 'Settings',
      },
    ],
  },

  progress: {
    type: 'progress',
    label: 'Progress Bar',
    icon: 'BarChart',
    category: 'interactive',
    description: 'Visual progress indicator',
    supportsChildren: false,
    defaultProps: {
      current: 0,
      total: 100,
      label: 'Progress',
      showPercentage: true,
    },
    propsSchema: [
      {
        name: 'current',
        label: 'Current Value',
        type: 'number',
        defaultValue: 0,
        group: 'Content',
      },
      {
        name: 'total',
        label: 'Total Value',
        type: 'number',
        defaultValue: 100,
        group: 'Content',
      },
      {
        name: 'label',
        label: 'Label',
        type: 'text',
        defaultValue: 'Progress',
        group: 'Content',
      },
      {
        name: 'showPercentage',
        label: 'Show Percentage',
        type: 'boolean',
        defaultValue: true,
        group: 'Settings',
      },
    ],
  },
};

// Block categories for organizing the block palette
export const LESSON_BLOCK_CATEGORIES = [
  {
    id: 'text',
    label: 'Text & Content',
    description: 'Text, headings, and content blocks',
    icon: 'Type',
  },
  {
    id: 'media',
    label: 'Media',
    description: 'Images, videos, audio, and files',
    icon: 'Image',
  },
  {
    id: 'interactive',
    label: 'Interactive',
    description: 'Flip cards, accordions, tabs, scenarios, and knowledge checks',
    icon: 'MousePointer',
  },
  {
    id: 'assessment',
    label: 'Assessment',
    description: 'Quizzes, polls, matching, and sorting exercises',
    icon: 'CheckCircle',
  },
  {
    id: 'structure',
    label: 'Layout',
    description: 'Sections, columns, grids, and dividers',
    icon: 'Layout',
  },
];

// Helper function to get blocks by category
export const getBlocksByCategory = (category: string): LessonBlockDefinition[] => {
  return Object.values(LESSON_BLOCK_DEFINITIONS).filter(
    (block) => block.category === category
  );
};

// Helper function to get a single block definition by type
export const getBlockDefinition = (type: LessonBlockType): LessonBlockDefinition | undefined => {
  return LESSON_BLOCK_DEFINITIONS[type];
};

// Generate unique block ID
export const generateBlockId = (): string => {
  return `block_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
};

// Create a new block with default props
export const createBlock = (type: LessonBlockType): import('./types').LessonBlock => {
  const definition = LESSON_BLOCK_DEFINITIONS[type];
  return {
    id: generateBlockId(),
    type,
    props: { ...definition.defaultProps },
  };
};
